export default function () {
  return{ 
    enchants:[
      { name:'Разящий клинок (JE)', id:'sweeping'},
      { name:'Отбрасывание', id:'knockback'},
      { name:'Острота', id:'sharpness'},
      { name:'Небесная кара', id:'smite'},
      { name:'Мародёрство (Добыча)', id:'looting'},
      { name:'Заговор огня', id:'fire_aspect'},
      { name:'Бич членистоногих', id:'bane_of_arthropods'},
      { name:'Эффективность', id:'efficiency'},
      { name:'Шёлковое касание', id:'silk_touch'},
      { name:'Удача', id:'fortune'},
      { name:'Ударная волна', id:'punch'},
      { name:'Сила', id:'power'},
      { name:'Воспламенение', id:'flame'},
      { name:'Бесконечность', id:'infinity'},
      { name:'Тягун (JE и BE)', id:'riptide'},
      { name:'Пронзатель', id:'impaling'},
      { name:'Громовержец (JE и BE)', id:'channeling'},
      { name:'Верность (JE и BE)', id:'loyalty'},
      { name:'Шипы', id:'thorns'},
      { name:'Прочность', id:'unbreaking'},
      { name:'Починка', id:'mending'},
      { name:'Проклятие утраты (JE и BE)', id:'vanishing_curse'},
      { name:'Проклятие несъёмности (JE и BE)', id:'binding_curse'},
      { name:'Приманка', id:'lure'},
      { name:'Морская удача', id:'luck_of_the_sea'},
      { name:'Огнеупорность', id:'fire_protection'},
      { name:'Защита от снарядов', id:'projectile_protection'},
      { name:'Защита', id:'protection'},
      { name:'Взрывоустойчивость', id:'blast_protection'},
      { name:'Подводное дыхание', id:'respiration'},
      { name:'Родство с водой (Подводник)', id:'aqua_affinity'},
      { name:'Ледяная Поступь (Ходьба по воде)', id:'frost_walker'},
      { name:'Невесомость', id:'feather_falling'},
    ],
   items: [ { name: 'Азалия', id: 'azalea'},
{ name: 'Акациевая грузовая лодка', id: 'acacia_chest_boat'},
{ name: 'Акациевая дверь', id: 'acacia_door'},
{ name: 'Акациевая калитка', id: 'acacia_fence_gate'},
{ name: 'Акациевая кнопка', id: 'acacia_button'},
{ name: 'Акациевая лодка', id: 'acacia_boat'},
{ name: 'Акациевая нажимная плита', id: 'acacia_pressure_plate'},
{ name: 'Акациевая плита', id: 'acacia_slab'},
{ name: 'Акациевая подвесная табличка', id: 'acacia_hanging_sign'},
{ name: 'Акациевая табличка', id: 'acacia_sign'},
{ name: 'Акациевое бревно', id: 'acacia_log'},
{ name: 'Акациевые доски', id: 'acacia_planks'},
{ name: 'Акациевые ступеньки', id: 'acacia_stairs'},
{ name: 'Акациевый забор', id: 'acacia_fence'},
{ name: 'Акациевый люк', id: 'acacia_trapdoor'},
{ name: 'Акация', id: 'acacia_wood'},
{ name: 'Аксолотль в ведре', id: 'axolotl_bucket'},
{ name: 'Активирующие рельсы', id: 'activator_rail'},
{ name: 'Алмаз', id: 'diamond'},
{ name: 'Алмазная кирка', id: 'diamond_pickaxe'},
{ name: 'Алмазная конская броня', id: 'diamond_horse_armor'},
{ name: 'Алмазная лопата', id: 'diamond_shovel'},
{ name: 'Алмазная мотыга', id: 'diamond_hoe'},
{ name: 'Алмазная руда', id: 'diamond_ore'},
{ name: 'Алмазные ботинки', id: 'diamond_boots'},
{ name: 'Алмазные поножи', id: 'diamond_leggings'},
{ name: 'Алмазный блок', id: 'diamond_block'},
{ name: 'Алмазный меч', id: 'diamond_sword'},
{ name: 'Алмазный нагрудник', id: 'diamond_chestplate'},
{ name: 'Алмазный топор', id: 'diamond_axe'},
{ name: 'Алмазный шлем', id: 'diamond_helmet'},
{ name: 'Алмазоносный глубинный сланец', id: 'deepslate_diamond_ore'},
{ name: 'Аметистовая друза', id: 'amethyst_cluster'},
{ name: 'Аметистовый блок', id: 'amethyst_block'},
{ name: 'Андезит', id: 'andesite'},
{ name: 'Андезитовая ограда', id: 'andesite_wall'},
{ name: 'Андезитовая плита', id: 'andesite_slab'},
{ name: 'Андезитовые ступеньки', id: 'andesite_stairs'},
{ name: 'Арбалет', id: 'crossbow'},
{ name: 'Арбуз', id: 'melon'},
{ name: 'Багровая дверь', id: 'crimson_door'},
{ name: 'Багровая калитка', id: 'crimson_fence_gate'},
{ name: 'Багровая кнопка', id: 'crimson_button'},
{ name: 'Багровая нажимная плита', id: 'crimson_pressure_plate'},
{ name: 'Багровая плита', id: 'crimson_slab'},
{ name: 'Багровая подвесная табличка', id: 'crimson_hanging_sign'},
{ name: 'Багровая табличка', id: 'crimson_sign'},
{ name: 'Багровые гифы', id: 'crimson_hyphae'},
{ name: 'Багровые доски', id: 'crimson_planks'},
{ name: 'Багровые корни', id: 'crimson_roots'},
{ name: 'Багровые ступеньки', id: 'crimson_stairs'},
{ name: 'Багровый гриб', id: 'crimson_fungus'},
{ name: 'Багровый забор', id: 'crimson_fence'},
{ name: 'Багровый люк', id: 'crimson_trapdoor'},
{ name: 'Багровый нилий', id: 'crimson_nylium'},
{ name: 'Багровый стебель', id: 'crimson_stem'},
{ name: 'Базальт', id: 'basalt'},
{ name: 'Бамбук', id: 'bamboo'},
{ name: 'Бамбуковая дверь', id: 'bamboo_door'},
{ name: 'Бамбуковая калитка', id: 'bamboo_fence_gate'},
{ name: 'Бамбуковая кнопка', id: 'bamboo_button'},
{ name: 'Бамбуковая мозаика', id: 'bamboo_mosaic'},
{ name: 'Бамбуковая нажимная плита', id: 'bamboo_pressure_plate'},
{ name: 'Бамбуковая плита', id: 'bamboo_slab'},
{ name: 'Бамбуковая подвесная табличка', id: 'bamboo_hanging_sign'},
{ name: 'Бамбуковая табличка', id: 'bamboo_sign'},
{ name: 'Бамбуковые доски', id: 'bamboo_planks'},
{ name: 'Бамбуковые ступеньки', id: 'bamboo_stairs'},
{ name: 'Бамбуковый забор', id: 'bamboo_fence'},
{ name: 'Бамбуковый люк', id: 'bamboo_trapdoor'},
{ name: 'Бамбуковый плот', id: 'bamboo_raft'},
{ name: 'Барьер', id: 'barrier'},
{ name: 'Бедрок', id: 'bedrock'},
{ name: 'Белая глазурованная керамика', id: 'white_glazed_terracotta'},
{ name: 'Белая керамика', id: 'white_terracotta'},
{ name: 'Белая кровать', id: 'white_bed'},
{ name: 'Белая свеча', id: 'white_candle'},
{ name: 'Белая стеклянная панель', id: 'white_stained_glass_pane'},
{ name: 'Белая шерсть', id: 'white_wool'},
{ name: 'Белое стекло', id: 'white_stained_glass'},
{ name: 'Белый бетон', id: 'white_concrete'},
{ name: 'Белый ковёр', id: 'white_carpet'},
{ name: 'Белый краситель', id: 'white_dye'},
{ name: 'Белый сухой бетон', id: 'white_concrete_powder'},
{ name: 'Белый тюльпан', id: 'white_tulip'},
{ name: 'Белый флаг', id: 'white_banner'},
{ name: 'Белый шалкеровый ящик', id: 'white_shulker_box'},
{ name: 'Берёза', id: 'birch_wood'},
{ name: 'Берёзовая грузовая лодка', id: 'birch_chest_boat'},
{ name: 'Берёзовая дверь', id: 'birch_door'},
{ name: 'Берёзовая калитка', id: 'birch_fence_gate'},
{ name: 'Берёзовая кнопка', id: 'birch_button'},
{ name: 'Берёзовая лодка', id: 'birch_boat'},
{ name: 'Берёзовая нажимная плита', id: 'birch_pressure_plate'},
{ name: 'Берёзовая плита', id: 'birch_slab'},
{ name: 'Берёзовая подвесная табличка', id: 'birch_hanging_sign'},
{ name: 'Берёзовая табличка', id: 'birch_sign'},
{ name: 'Берёзовое бревно', id: 'birch_log'},
{ name: 'Берёзовые доски', id: 'birch_planks'},
{ name: 'Берёзовые листья', id: 'birch_leaves'},
{ name: 'Берёзовые ступеньки', id: 'birch_stairs'},
{ name: 'Берёзовый забор', id: 'birch_fence'},
{ name: 'Берёзовый люк', id: 'birch_trapdoor'},
{ name: 'Бирка', id: 'name_tag'},
{ name: 'Бирюзовая глазурованная керамика', id: 'cyan_glazed_terracotta'},
{ name: 'Бирюзовая керамика', id: 'cyan_terracotta'},
{ name: 'Бирюзовая кровать', id: 'cyan_bed'},
{ name: 'Бирюзовая свеча', id: 'cyan_candle'},
{ name: 'Бирюзовая стеклянная панель', id: 'cyan_stained_glass_pane'},
{ name: 'Бирюзовая шерсть', id: 'cyan_wool'},
{ name: 'Бирюзовое стекло', id: 'cyan_stained_glass'},
{ name: 'Бирюзовый бетон', id: 'cyan_concrete'},
{ name: 'Бирюзовый ковёр', id: 'cyan_carpet'},
{ name: 'Бирюзовый краситель', id: 'cyan_dye'},
{ name: 'Бирюзовый сухой бетон', id: 'cyan_concrete_powder'},
{ name: 'Бирюзовый флаг', id: 'cyan_banner'},
{ name: 'Бирюзовый шалкеровый ящик', id: 'cyan_shulker_box'},
{ name: 'Блок бамбука', id: 'bamboo_block'},
{ name: 'Блок искажённого нароста', id: 'warped_wart_block'},
{ name: 'Блок коралла-мозговика', id: 'brain_coral_block'},
{ name: 'Блок коричневого гриба', id: 'brown_mushroom_block'},
{ name: 'Блок красного гриба', id: 'red_mushroom_block'},
{ name: 'Блок мха', id: 'moss_block'},
{ name: 'Блок мёда', id: 'honey_block'},
{ name: 'Блок мёртвого коралла-мозговика', id: 'dead_brain_coral_block'},
{ name: 'Блок мёртвого огненного коралла', id: 'dead_fire_coral_block'},
{ name: 'Блок мёртвого пузырчатого коралла', id: 'dead_bubble_coral_block'},
{ name: 'Блок мёртвого рогового коралла', id: 'dead_horn_coral_block'},
{ name: 'Блок мёртвого трубчатого коралла', id: 'dead_tube_coral_block'},
{ name: 'Блок незерского нароста', id: 'nether_wart_block'},
{ name: 'Блок обтёсанного бамбука', id: 'stripped_bamboo_block'},
{ name: 'Блок огненного коралла', id: 'fire_coral_block'},
{ name: 'Блок пузырчатого коралла', id: 'bubble_coral_block'},
{ name: 'Блок пчелиных сот', id: 'honeycomb_block'},
{ name: 'Блок рогового коралла', id: 'horn_coral_block'},
{ name: 'Блок рудного железа', id: 'raw_iron_block'},
{ name: 'Блок рудного золота', id: 'raw_gold_block'},
{ name: 'Блок рудной меди', id: 'raw_copper_block'},
{ name: 'Блок слизи', id: 'slime_block'},
{ name: 'Блок снега', id: 'snow_block'},
{ name: 'Блок сушёной ламинарии', id: 'dried_kelp_block'},
{ name: 'Блок трубчатого коралла', id: 'tube_coral_block'},
{ name: 'Блок-конструктор', id: 'structure_block'},
{ name: 'Большая бросянка', id: 'big_dripleaf'},
{ name: 'Большегрузная весовая пластина', id: 'heavy_weighted_pressure_plate'},
{ name: 'Большой аметистовый бутон', id: 'large_amethyst_bud'},
{ name: 'Бочка', id: 'barrel'},
{ name: 'Бревно тропического дерева', id: 'jungle_log'},
{ name: 'Бревно тёмного дуба', id: 'dark_oak_log'},
{ name: 'Булыжная ограда', id: 'cobblestone_wall'},
{ name: 'Булыжная плита', id: 'cobblestone_slab'},
{ name: 'Булыжник', id: 'cobblestone'},
{ name: 'Булыжные ступеньки', id: 'cobblestone_stairs'},
{ name: 'Бумага', id: 'paper'},
{ name: 'Бутылочка', id: 'glass_bottle'},
{ name: 'Бутылочка воды', id: 'potion{Potion:water}'},
{ name: 'Бутылочка мёда', id: 'honey_bottle'},
{ name: 'Бутылочка с водяной взвесью', id: 'lingering_potion{Potion:water}'},
{ name: 'Вагонетка', id: 'minecart'},
{ name: 'Вагонетка с динамитом', id: 'tnt_minecart'},
{ name: 'Вагонетка с командным блоком', id: 'command_block_minecart'},
{ name: 'Ведро', id: 'bucket'},
{ name: 'Ведро воды', id: 'water_bucket'},
{ name: 'Ведро лавы', id: 'lava_bucket'},
{ name: 'Ведро молока', id: 'milk_bucket'},
{ name: 'Ведро с рыхлым снегом', id: 'powder_snow_bucket'},
{ name: 'Веерный коралл-мозговик', id: 'brain_coral_fan'},
{ name: 'Веерный огненный коралл', id: 'fire_coral_fan'},
{ name: 'Веерный пузырчатый коралл', id: 'bubble_coral_fan'},
{ name: 'Веерный роговый коралл', id: 'horn_coral_fan'},
{ name: 'Веерный трубчатый коралл', id: 'tube_coral_fan'},
{ name: 'Верстак', id: 'crafting_table'},
{ name: 'Весовая пластина', id: 'light_weighted_pressure_plate'},
{ name: 'Взрывная бутылочка воды', id: 'splash_potion{Potion:water}'},
{ name: 'Взрывная стрела', id: 'tipped_arrow{Potion:water}'},
{ name: 'Взрывное зелье Везения', id: 'splash_potion{Potion:luck}'},
{ name: 'Взрывное зелье Водного дыхания', id: 'splash_potion{Potion:water_breathing}'},
{ name: 'Взрывное зелье Водного дыхания продлённое', id: 'splash_potion{Potion:long_water_breathing}'},
{ name: 'Взрывное зелье Вреда', id: 'splash_potion{Potion:harming}'},
{ name: 'Взрывное зелье Вреда усиленное', id: 'splash_potion{Potion:strong_harming}'},
{ name: 'Взрывное зелье Замедления', id: 'splash_potion{Potion:slowness}'},
{ name: 'Взрывное зелье Замедления продлённое', id: 'splash_potion{Potion:long_slowness}'},
{ name: 'Взрывное зелье Замедления усиленное', id: 'splash_potion{Potion:strong_slowness}'},
{ name: 'Взрывное зелье Исцеления', id: 'splash_potion{Potion:healing}'},
{ name: 'Взрывное зелье Исцеления усиленное', id: 'splash_potion{Potion:strong_healing}'},
{ name: 'Взрывное зелье Невидимости', id: 'splash_potion{Potion:invisibility}'},
{ name: 'Взрывное зелье Невидимости продлённое', id: 'splash_potion{Potion:long_invisibility}'},
{ name: 'Взрывное зелье Ночного зрения', id: 'splash_potion{Potion:night_vision}'},
{ name: 'Взрывное зелье Ночного зрения продлённое', id: 'splash_potion{Potion:long_night_vision}'},
{ name: 'Взрывное зелье Огнестойкости', id: 'splash_potion{Potion:fire_resistance}'},
{ name: 'Взрывное зелье Огнестойкости продлённое', id: 'splash_potion{Potion:long_fire_resistance}'},
{ name: 'Взрывное зелье Отравления', id: 'splash_potion{Potion:poison}'},
{ name: 'Взрывное зелье Отравления продлённое', id: 'splash_potion{Potion:long_poison}'},
{ name: 'Взрывное зелье Отравления усиленное', id: 'splash_potion{Potion:strong_poison}'},
{ name: 'Взрывное зелье Плавного падения', id: 'splash_potion{Potion:slow_falling}'},
{ name: 'Взрывное зелье Плавного падения продлённое', id: 'splash_potion{Potion:long_slow_falling}'},
{ name: 'Взрывное зелье Прыгучести', id: 'splash_potion{Potion:leaping}'},
{ name: 'Взрывное зелье Прыгучести продлённое', id: 'splash_potion{Potion:long_leaping}'},
{ name: 'Взрывное зелье Прыгучести усиленное', id: 'splash_potion{Potion:strong_leaping}'},
{ name: 'Взрывное зелье Регенерации', id: 'splash_potion{Potion:regeneration}'},
{ name: 'Взрывное зелье Регенерации продлённое', id: 'splash_potion{Potion:long_regeneration}'},
{ name: 'Взрывное зелье Регенерации усиленное', id: 'splash_potion{Potion:strong_regeneration}'},
{ name: 'Взрывное зелье Силы', id: 'splash_potion{Potion:strength}'},
{ name: 'Взрывное зелье Силы продлённое', id: 'splash_potion{Potion:long_strength}'},
{ name: 'Взрывное зелье Силы усиленное', id: 'splash_potion{Potion:strong_strength}'},
{ name: 'Взрывное зелье Слабости', id: 'splash_potion{Potion:weakness}'},
{ name: 'Взрывное зелье Слабости продлённое', id: 'splash_potion{Potion:long_weakness}'},
{ name: 'Взрывное зелье Стремительности', id: 'splash_potion{Potion:swiftness}'},
{ name: 'Взрывное зелье Стремительности продлённое', id: 'splash_potion{Potion:long_swiftness}'},
{ name: 'Взрывное зелье Стремительности усиленное', id: 'splash_potion{Potion:strong_swiftness}'},
{ name: 'Взрывное зелье Черепашьей мощи', id: 'splash_potion{Potion:turtle_master}'},
{ name: 'Взрывное зелье Черепашьей мощи продлённое', id: 'splash_potion{Potion:long_turtle_master}'},
{ name: 'Взрывное зелье Черепашьей мощи усиленное', id: 'splash_potion{Potion:strong_turtle_master}'},
{ name: 'Вишня', id: 'cherry_wood'},
{ name: 'Вишнёвая грузовая лодка', id: 'cherry_chest_boat'},
{ name: 'Вишнёвая дверь', id: 'cherry_door'},
{ name: 'Вишнёвая калитка', id: 'cherry_fence_gate'},
{ name: 'Вишнёвая кнопка', id: 'cherry_button'},
{ name: 'Вишнёвая лодка', id: 'cherry_boat'},
{ name: 'Вишнёвая нажимная плита', id: 'cherry_pressure_plate'},
{ name: 'Вишнёвая плита', id: 'cherry_slab'},
{ name: 'Вишнёвая подвесная табличка', id: 'cherry_hanging_sign'},
{ name: 'Вишнёвая табличка', id: 'cherry_sign'},
{ name: 'Вишнёвое бревно', id: 'cherry_log'},
{ name: 'Вишнёвые доски', id: 'cherry_planks'},
{ name: 'Вишнёвые листья', id: 'cherry_leaves'},
{ name: 'Вишнёвые ступеньки', id: 'cherry_stairs'},
{ name: 'Вишнёвый забор', id: 'cherry_fence'},
{ name: 'Вишнёвый люк', id: 'cherry_trapdoor'},
{ name: 'Возвратный компас', id: 'recovery_compass'},
{ name: 'Воздух', id: 'air'},
{ name: 'Воронка', id: 'hopper'},
{ name: 'Вощёная окисленная резная медная плита', id: 'waxed_oxidized_cut_copper_slab'},
{ name: 'Вощёная потемневшая резная медная плита', id: 'waxed_exposed_cut_copper_slab'},
{ name: 'Вощёная резная медная плита', id: 'waxed_cut_copper_slab'},
{ name: 'Вощёная состаренная резная медная плита', id: 'waxed_weathered_cut_copper_slab'},
{ name: 'Вощёные окисленные резные медные ступеньки', id: 'waxed_oxidized_cut_copper_stairs'},
{ name: 'Вощёные потемневшие резные медные ступеньки', id: 'waxed_exposed_cut_copper_stairs'},
{ name: 'Вощёные резные медные ступеньки', id: 'waxed_cut_copper_stairs'},
{ name: 'Вощёные состаренные резные медные ступеньки', id: 'waxed_weathered_cut_copper_stairs'},
{ name: 'Вощёный медный блок', id: 'waxed_copper_block'},
{ name: 'Вощёный окисленный медный блок', id: 'waxed_oxidized_copper'},
{ name: 'Вощёный окисленный резной медный блок', id: 'waxed_oxidized_cut_copper'},
{ name: 'Вощёный потемневший медный блок', id: 'waxed_exposed_copper'},
{ name: 'Вощёный потемневший резной медный блок', id: 'waxed_exposed_cut_copper'},
{ name: 'Вощёный резной медный блок', id: 'waxed_cut_copper'},
{ name: 'Вощёный состаренный медный блок', id: 'waxed_weathered_copper'},
{ name: 'Вощёный состаренный резной медный блок', id: 'waxed_weathered_cut_copper'},
{ name: 'Выбрасыватель', id: 'dropper'},
{ name: 'Вырезанная тыква', id: 'carved_pumpkin'},
{ name: 'Высокая трава', id: 'tall_grass'},
{ name: 'Вьющаяся лоза', id: 'twisting_vines'},
{ name: 'Гладкий базальт', id: 'smooth_basalt'},
{ name: 'Гладкий камень', id: 'smooth_stone'},
{ name: 'Гладкий кварц', id: 'smooth_quartz'},
{ name: 'Гладкий красный песчаник', id: 'smooth_red_sandstone'},
{ name: 'Гладкий песчаник', id: 'smooth_sandstone'},
{ name: 'Глина', id: 'clay'},
{ name: 'Глиняный черепок Вой', id: 'howl_pottery_sherd'},
{ name: 'Глиняный черепок Друг', id: 'friend_pottery_sherd'},
{ name: 'Глиняный черепок Зельевар', id: 'brewer_pottery_sherd'},
{ name: 'Глиняный черепок Изобилие', id: 'plenty_pottery_sherd'},
{ name: 'Глиняный черепок Исследователь', id: 'explorer_pottery_sherd'},
{ name: 'Глиняный черепок Клинок', id: 'blade_pottery_sherd'},
{ name: 'Глиняный черепок Лучник', id: 'archer_pottery_sherd'},
{ name: 'Глиняный черепок Награда', id: 'prize_pottery_sherd'},
{ name: 'Глиняный черепок Нюхач', id: 'snort_pottery_sherd'},
{ name: 'Глиняный черепок Опасность', id: 'danger_pottery_sherd'},
{ name: 'Глиняный черепок Пламя', id: 'burn_pottery_sherd'},
{ name: 'Глиняный черепок Пучок', id: 'sheaf_pottery_sherd'},
{ name: 'Глиняный черепок Разбитое сердце', id: 'heartbreak_pottery_sherd'},
{ name: 'Глиняный черепок Руки вверх', id: 'arms_up_pottery_sherd'},
{ name: 'Глиняный черепок Рыбак', id: 'angler_pottery_sherd'},
{ name: 'Глиняный черепок Сердце', id: 'heart_pottery_sherd'},
{ name: 'Глиняный черепок Скорбь', id: 'mourner_pottery_sherd'},
{ name: 'Глиняный черепок Убежище', id: 'shelter_pottery_sherd'},
{ name: 'Глиняный черепок Череп', id: 'skull_pottery_sherd'},
{ name: 'Глиняный черепок Шахтёр', id: 'miner_pottery_sherd'},
{ name: 'Глубинносланцевые кирпичи', id: 'deepslate_bricks'},
{ name: 'Глубинносланцевый плитняк', id: 'deepslate_tiles'},
{ name: 'Глубинный сланец', id: 'deepslate'},
{ name: 'Гнилая плоть', id: 'rotten_flesh'},
{ name: 'Голова дракона', id: 'dragon_head'},
{ name: 'Голова зомби', id: 'zombie_head'},
{ name: 'Голова игрока', id: 'player_head'},
{ name: 'Голова крипера', id: 'creeper_head'},
{ name: 'Голова пиглина', id: 'piglin_head'},
{ name: 'Головастик в ведре', id: 'tadpole_bucket'},
{ name: 'Голубая глазурованная керамика', id: 'light_blue_glazed_terracotta'},
{ name: 'Голубая керамика', id: 'light_blue_terracotta'},
{ name: 'Голубая кровать', id: 'light_blue_bed'},
{ name: 'Голубая свеча', id: 'light_blue_candle'},
{ name: 'Голубая стеклянная панель', id: 'light_blue_stained_glass_pane'},
{ name: 'Голубая шерсть', id: 'light_blue_wool'},
{ name: 'Голубое стекло', id: 'light_blue_stained_glass'},
{ name: 'Голубой бетон', id: 'light_blue_concrete'},
{ name: 'Голубой ковёр', id: 'light_blue_carpet'},
{ name: 'Голубой краситель', id: 'light_blue_dye'},
{ name: 'Голубой сухой бетон', id: 'light_blue_concrete_powder'},
{ name: 'Голубой флаг', id: 'light_blue_banner'},
{ name: 'Голубой шалкеровый ящик', id: 'light_blue_shulker_box'},
{ name: 'Гравий', id: 'gravel'},
{ name: 'Гранит', id: 'granite'},
{ name: 'Гранитная ограда', id: 'granite_wall'},
{ name: 'Гранитная плита', id: 'granite_slab'},
{ name: 'Гранитные ступеньки', id: 'granite_stairs'},
{ name: 'Грибосвет', id: 'shroomlight'},
{ name: 'Громоотвод', id: 'lightning_rod'},
{ name: 'Грузовая вагонетка', id: 'chest_minecart'},
{ name: 'Грузовая лодка из тропического дерева', id: 'jungle_chest_boat'},
{ name: 'Грузовая лодка из тёмного дуба', id: 'dark_oak_chest_boat'},
{ name: 'Грузовой бамбуковый плот', id: 'bamboo_chest_raft'},
{ name: 'Грязные мангровые корни', id: 'muddy_mangrove_roots'},
{ name: 'Грязь', id: 'mud'},
{ name: 'Губка', id: 'sponge'},
{ name: 'Густое взрывное зелье', id: 'splash_potion{Potion:thick}'},
{ name: 'Густое зелье', id: 'potion{Potion:thick}'},
{ name: 'Густое туманное зелье', id: 'lingering_potion{Potion:thick}'},
{ name: 'Датчик дневного света', id: 'daylight_detector'},
{ name: 'Дверь из тропического дерева', id: 'jungle_door'},
{ name: 'Дверь из тёмного дуба', id: 'dark_oak_door'},
{ name: 'Деревянная кирка', id: 'wooden_pickaxe'},
{ name: 'Деревянная лопата', id: 'wooden_shovel'},
{ name: 'Деревянная мотыга', id: 'wooden_hoe'},
{ name: 'Деревянный меч', id: 'wooden_sword'},
{ name: 'Деревянный топор', id: 'wooden_axe'},
{ name: 'Динамит', id: 'tnt'},
{ name: 'Диорит', id: 'diorite'},
{ name: 'Диоритовая ограда', id: 'diorite_wall'},
{ name: 'Диоритовая плита', id: 'diorite_slab'},
{ name: 'Диоритовые ступеньки', id: 'diorite_stairs'},
{ name: 'Доски из тропического дерева', id: 'jungle_planks'},
{ name: 'Доски из тёмного дуба', id: 'dark_oak_planks'},
{ name: 'Драконье дыхание', id: 'dragon_breath'},
{ name: 'Древесный уголь', id: 'charcoal'},
{ name: 'Древние обломки', id: 'ancient_debris'},
{ name: 'Дуб', id: 'oak_wood'},
{ name: 'Дубовая грузовая лодка', id: 'oak_chest_boat'},
{ name: 'Дубовая дверь', id: 'oak_door'},
{ name: 'Дубовая калитка', id: 'oak_fence_gate'},
{ name: 'Дубовая кнопка', id: 'oak_button'},
{ name: 'Дубовая лодка', id: 'oak_boat'},
{ name: 'Дубовая нажимная плита', id: 'oak_pressure_plate'},
{ name: 'Дубовая плита', id: 'oak_slab'},
{ name: 'Дубовая подвесная табличка', id: 'oak_hanging_sign'},
{ name: 'Дубовая табличка', id: 'oak_sign'},
{ name: 'Дубовое бревно', id: 'oak_log'},
{ name: 'Дубовые доски', id: 'oak_planks'},
{ name: 'Дубовые листья', id: 'oak_leaves'},
{ name: 'Дубовые ступеньки', id: 'oak_stairs'},
{ name: 'Дубовый забор', id: 'oak_fence'},
{ name: 'Дубовый люк', id: 'oak_trapdoor'},
{ name: 'Дёрн', id: 'grass_block'},
{ name: 'Еловая грузовая лодка', id: 'spruce_chest_boat'},
{ name: 'Еловая дверь', id: 'spruce_door'},
{ name: 'Еловая калитка', id: 'spruce_fence_gate'},
{ name: 'Еловая кнопка', id: 'spruce_button'},
{ name: 'Еловая лодка', id: 'spruce_boat'},
{ name: 'Еловая нажимная плита', id: 'spruce_pressure_plate'},
{ name: 'Еловая плита', id: 'spruce_slab'},
{ name: 'Еловая подвесная табличка', id: 'spruce_hanging_sign'},
{ name: 'Еловая табличка', id: 'spruce_sign'},
{ name: 'Еловое бревно', id: 'spruce_log'},
{ name: 'Еловые доски', id: 'spruce_planks'},
{ name: 'Еловые ступеньки', id: 'spruce_stairs'},
{ name: 'Еловый забор', id: 'spruce_fence'},
{ name: 'Еловый люк', id: 'spruce_trapdoor'},
{ name: 'Ель', id: 'spruce_wood'},
{ name: 'Жареная баранина', id: 'cooked_mutton'},
{ name: 'Жареная крольчатина', id: 'cooked_rabbit'},
{ name: 'Жареная курица', id: 'cooked_chicken'},
{ name: 'Жареная свинина', id: 'cooked_porkchop'},
{ name: 'Жареная треска', id: 'cooked_cod'},
{ name: 'Жареный лосось', id: 'cooked_salmon'},
{ name: 'Железная дверь', id: 'iron_door'},
{ name: 'Железная кирка', id: 'iron_pickaxe'},
{ name: 'Железная конская броня', id: 'iron_horse_armor'},
{ name: 'Железная лопата', id: 'iron_shovel'},
{ name: 'Железная мотыга', id: 'iron_hoe'},
{ name: 'Железная руда', id: 'iron_ore'},
{ name: 'Железные ботинки', id: 'iron_boots'},
{ name: 'Железные поножи', id: 'iron_leggings'},
{ name: 'Железные прутья', id: 'iron_bars'},
{ name: 'Железный блок', id: 'iron_block'},
{ name: 'Железный люк', id: 'iron_trapdoor'},
{ name: 'Железный меч', id: 'iron_sword'},
{ name: 'Железный нагрудник', id: 'iron_chestplate'},
{ name: 'Железный слиток', id: 'iron_ingot'},
{ name: 'Железный топор', id: 'iron_axe'},
{ name: 'Железный шлем', id: 'iron_helmet'},
{ name: 'Железоносный глубинный сланец', id: 'deepslate_iron_ore'},
{ name: 'Жёлтая глазурованная керамика', id: 'yellow_glazed_terracotta'},
{ name: 'Жёлтая керамика', id: 'yellow_terracotta'},
{ name: 'Жёлтая кровать', id: 'yellow_bed'},
{ name: 'Жёлтая свеча', id: 'yellow_candle'},
{ name: 'Жёлтая стеклянная панель', id: 'yellow_stained_glass_pane'},
{ name: 'Жёлтая шерсть', id: 'yellow_wool'},
{ name: 'Жёлтое стекло', id: 'yellow_stained_glass'},
{ name: 'Жёлтый бетон', id: 'yellow_concrete'},
{ name: 'Жёлтый ковёр', id: 'yellow_carpet'},
{ name: 'Жёлтый краситель', id: 'yellow_dye'},
{ name: 'Жёлтый сухой бетон', id: 'yellow_concrete_powder'},
{ name: 'Жёлтый флаг', id: 'yellow_banner'},
{ name: 'Жёлтый шалкеровый ящик', id: 'yellow_shulker_box'},
{ name: 'Забор из незерского кирпича', id: 'nether_brick_fence'},
{ name: 'Забор из тропического дерева', id: 'jungle_fence'},
{ name: 'Забор из тёмного дуба', id: 'dark_oak_fence'},
{ name: 'Завершённая книга', id: 'written_book'},
{ name: 'Загадочное рагу - Иссушение', id: 'suspicious_stew{Effects:[{EffectDuration:160,EffectId:20}]}'},
{ name: 'Загадочное рагу - Насыщенность', id: 'suspicious_stew{Effects:[{EffectDuration:7,EffectId:23}]}'},
{ name: 'Загадочное рагу - Ночное зрение', id: 'suspicious_stew{Effects:[{EffectDuration:100,EffectId:16}]}'},
{ name: 'Загадочное рагу - Огнестойкость', id: 'suspicious_stew{Effects:[{EffectDuration:80,EffectId:12}]}'},
{ name: 'Загадочное рагу - Отравление', id: 'suspicious_stew{Effects:[{EffectDuration:240,EffectId:19}]}'},
{ name: 'Загадочное рагу - Прыгучесть', id: 'suspicious_stew{Effects:[{EffectDuration:120,EffectId:8}]}'},
{ name: 'Загадочное рагу - Регенерация', id: 'suspicious_stew{Effects:[{EffectDuration:160,EffectId:10}]}'},
{ name: 'Загадочное рагу - Слабость', id: 'suspicious_stew{Effects:[{EffectDuration:180,EffectId:18}]}'},
{ name: 'Загадочное рагу - Слепота', id: 'suspicious_stew{Effects:[{EffectDuration:160,EffectId:15}]}'},
{ name: 'Загрузочная вагонетка', id: 'hopper_minecart'},
{ name: 'Замшелая булыжная ограда', id: 'mossy_cobblestone_wall'},
{ name: 'Замшелая булыжная плита', id: 'mossy_cobblestone_slab'},
{ name: 'Замшелые булыжные ступеньки', id: 'mossy_cobblestone_stairs'},
{ name: 'Замшелые каменные кирпичи', id: 'mossy_stone_bricks'},
{ name: 'Замшелый булыжник', id: 'mossy_cobblestone'},
{ name: 'Заражённые замшелые каменные кирпичи', id: 'infested_mossy_stone_bricks'},
{ name: 'Заражённые каменные кирпичи', id: 'infested_stone_bricks'},
{ name: 'Заражённые потрескавшиеся каменные кирпичи', id: 'infested_cracked_stone_bricks'},
{ name: 'Заражённые резные каменные кирпичи', id: 'infested_chiseled_stone_bricks'},
{ name: 'Заражённый булыжник', id: 'infested_cobblestone'},
{ name: 'Заражённый глубинный сланец', id: 'infested_deepslate'},
{ name: 'Заражённый камень', id: 'infested_stone'},
{ name: 'Заурядное взрывное зелье', id: 'splash_potion{Potion:mundane}'},
{ name: 'Заурядное зелье', id: 'potion{Potion:mundane}'},
{ name: 'Заурядное туманное зелье', id: 'lingering_potion{Potion:mundane}'},
{ name: 'Зачарованное золотое яблоко', id: 'enchanted_golden_apple'},
{ name: 'Звезда Незера', id: 'nether_star'},
{ name: 'Зелье Везения', id: 'potion{Potion:luck}'},
{ name: 'Зелье Водного дыхания', id: 'potion{Potion:water_breathing}'},
{ name: 'Зелье Водного дыхания продлённое', id: 'potion{Potion:long_water_breathing}'},
{ name: 'Зелье Вреда', id: 'potion{Potion:harming}'},
{ name: 'Зелье Вреда усиленное', id: 'potion{Potion:strong_harming}'},
{ name: 'Зелье Замедления', id: 'potion{Potion:slowness}'},
{ name: 'Зелье Замедления продлённое', id: 'potion{Potion:long_slowness}'},
{ name: 'Зелье Замедления усиленное', id: 'potion{Potion:strong_slowness}'},
{ name: 'Зелье Исцеления', id: 'potion{Potion:healing}'},
{ name: 'Зелье Исцеления усиленное', id: 'potion{Potion:strong_healing}'},
{ name: 'Зелье Невидимости', id: 'potion{Potion:invisibility}'},
{ name: 'Зелье Невидимости продлённое', id: 'potion{Potion:long_invisibility}'},
{ name: 'Зелье Ночного зрения', id: 'potion{Potion:night_vision}'},
{ name: 'Зелье Ночного зрения продлённое', id: 'potion{Potion:long_night_vision}'},
{ name: 'Зелье Огнестойкости', id: 'potion{Potion:fire_resistance}'},
{ name: 'Зелье Огнестойкости продлённое', id: 'potion{Potion:long_fire_resistance}'},
{ name: 'Зелье Отравления', id: 'potion{Potion:poison}'},
{ name: 'Зелье Отравления продлённое', id: 'potion{Potion:long_poison}'},
{ name: 'Зелье Отравления усиленное', id: 'potion{Potion:strong_poison}'},
{ name: 'Зелье Плавного падения', id: 'potion{Potion:slow_falling}'},
{ name: 'Зелье Плавного падения продлённое', id: 'potion{Potion:long_slow_falling}'},
{ name: 'Зелье Прыгучести', id: 'potion{Potion:leaping}'},
{ name: 'Зелье Прыгучести продлённое', id: 'potion{Potion:long_leaping}'},
{ name: 'Зелье Прыгучести усиленное', id: 'potion{Potion:strong_leaping}'},
{ name: 'Зелье Регенерации', id: 'potion{Potion:regeneration}'},
{ name: 'Зелье Регенерации продлённое', id: 'potion{Potion:long_regeneration}'},
{ name: 'Зелье Регенерации усиленное', id: 'potion{Potion:strong_regeneration}'},
{ name: 'Зелье Силы', id: 'potion{Potion:strength}'},
{ name: 'Зелье Силы продлённое', id: 'potion{Potion:long_strength}'},
{ name: 'Зелье Силы усиленное', id: 'potion{Potion:strong_strength}'},
{ name: 'Зелье Слабости', id: 'potion{Potion:weakness}'},
{ name: 'Зелье Слабости продлённое', id: 'potion{Potion:long_weakness}'},
{ name: 'Зелье Стремительности', id: 'potion{Potion:swiftness}'},
{ name: 'Зелье Стремительности продлённое', id: 'potion{Potion:long_swiftness}'},
{ name: 'Зелье Стремительности усиленное', id: 'potion{Potion:strong_swiftness}'},
{ name: 'Зелье Черепашьей мощи', id: 'potion{Potion:turtle_master}'},
{ name: 'Зелье Черепашьей мощи продлённое', id: 'potion{Potion:long_turtle_master}'},
{ name: 'Зелье Черепашьей мощи усиленное', id: 'potion{Potion:strong_turtle_master}'},
{ name: 'Зельеварка', id: 'brewing_stand'},
{ name: 'Зелёная глазурованная керамика', id: 'green_glazed_terracotta'},
{ name: 'Зелёная керамика', id: 'green_terracotta'},
{ name: 'Зелёная кровать', id: 'green_bed'},
{ name: 'Зелёная свеча', id: 'green_candle'},
{ name: 'Зелёная стеклянная панель', id: 'green_stained_glass_pane'},
{ name: 'Зелёная шерсть', id: 'green_wool'},
{ name: 'Зелёное стекло', id: 'green_stained_glass'},
{ name: 'Зелёный бетон', id: 'green_concrete'},
{ name: 'Зелёный ковёр', id: 'green_carpet'},
{ name: 'Зелёный краситель', id: 'green_dye'},
{ name: 'Зелёный сухой бетон', id: 'green_concrete_powder'},
{ name: 'Зелёный флаг', id: 'green_banner'},
{ name: 'Зелёный шалкеровый ящик', id: 'green_shulker_box'},
{ name: 'Земля', id: 'dirt'},
{ name: 'Зловещий флаг', id: 'white_banner{BlockEntityTag:{Patterns:[{Pattern:mr,Color:9},{Pattern:bs,Color:8},{Pattern:cs,Color:7'},
{ name: 'Золотая кирка', id: 'golden_pickaxe'},
{ name: 'Золотая конская броня', id: 'golden_horse_armor'},
{ name: 'Золотая лопата', id: 'golden_shovel'},
{ name: 'Золотая морковь', id: 'golden_carrot'},
{ name: 'Золотая мотыга', id: 'golden_hoe'},
{ name: 'Золотая руда', id: 'gold_ore'},
{ name: 'Золотое яблоко', id: 'golden_apple'},
{ name: 'Золотой блок', id: 'gold_block'},
{ name: 'Золотой меч', id: 'golden_sword'},
{ name: 'Золотой нагрудник', id: 'golden_chestplate'},
{ name: 'Золотой слиток', id: 'gold_ingot'},
{ name: 'Золотой топор', id: 'golden_axe'},
{ name: 'Золотой шлем', id: 'golden_helmet'},
{ name: 'Золотоносный глубинный сланец', id: 'deepslate_gold_ore'},
{ name: 'Золотые ботинки', id: 'golden_boots'},
{ name: 'Золотые поножи', id: 'golden_leggings'},
{ name: 'Золочёный чернит', id: 'gilded_blackstone'},
{ name: 'Иглобрюх', id: 'pufferfish'},
{ name: 'Иглобрюх в ведре', id: 'pufferfish_bucket'},
{ name: 'Изумруд', id: 'emerald'},
{ name: 'Изумрудная руда', id: 'emerald_ore'},
{ name: 'Изумрудный блок', id: 'emerald_block'},
{ name: 'Изумрудоносный глубинный сланец', id: 'deepslate_emerald_ore'},
{ name: 'Искажённая дверь', id: 'warped_door'},
{ name: 'Искажённая калитка', id: 'warped_fence_gate'},
{ name: 'Искажённая кнопка', id: 'warped_button'},
{ name: 'Искажённая нажимная плита', id: 'warped_pressure_plate'},
{ name: 'Искажённая плита', id: 'warped_slab'},
{ name: 'Искажённая подвесная табличка', id: 'warped_hanging_sign'},
{ name: 'Искажённая табличка', id: 'warped_sign'},
{ name: 'Искажённые гифы', id: 'warped_hyphae'},
{ name: 'Искажённые доски', id: 'warped_planks'},
{ name: 'Искажённые корни', id: 'warped_roots'},
{ name: 'Искажённые ступеньки', id: 'warped_stairs'},
{ name: 'Искажённый гриб', id: 'warped_fungus'},
{ name: 'Искажённый забор', id: 'warped_fence'},
{ name: 'Искажённый люк', id: 'warped_trapdoor'},
{ name: 'Искажённый нилий', id: 'warped_nylium'},
{ name: 'Искажённый стебель', id: 'warped_stem'},
{ name: 'Какао-бобы', id: 'cocoa_beans'},
{ name: 'Кактус', id: 'cactus'},
{ name: 'Калитка из тропического дерева', id: 'jungle_fence_gate'},
{ name: 'Калитка из тёмного дуба', id: 'dark_oak_fence_gate'},
{ name: 'Кальцит', id: 'calcite'},
{ name: 'Каменистая земля', id: 'coarse_dirt'},
{ name: 'Каменная кирка', id: 'stone_pickaxe'},
{ name: 'Каменная кнопка', id: 'stone_button'},
{ name: 'Каменная лопата', id: 'stone_shovel'},
{ name: 'Каменная мотыга', id: 'stone_hoe'},
{ name: 'Каменная нажимная плита', id: 'stone_pressure_plate'},
{ name: 'Каменная плита', id: 'stone_slab'},
{ name: 'Каменные кирпичи', id: 'stone_bricks'},
{ name: 'Каменные ступеньки', id: 'stone_stairs'},
{ name: 'Каменный меч', id: 'stone_sword'},
{ name: 'Каменный топор', id: 'stone_axe'},
{ name: 'Камень', id: 'stone'},
{ name: 'Камнерез', id: 'stonecutter'},
{ name: 'Капельник', id: 'pointed_dripstone'},
{ name: 'Карта', id: 'filled_map'},
{ name: 'Картина - Албанец', id: 'painting{EntityTag:{variant:alban}}'},
{ name: 'Картина - Ацтек', id: 'painting{EntityTag:{variant:aztec}}'},
{ name: 'Картина - Ацтек 2', id: 'painting{EntityTag:{variant:aztec2}}'},
{ name: 'Картина - Бассейн', id: 'painting{EntityTag:{variant:pool}}'},
{ name: 'Картина - Бюст', id: 'painting{EntityTag:{variant:bust}}'},
{ name: 'Картина - Ветер', id: 'painting{EntityTag:{variant:wind}}'},
{ name: 'Картина - Визер', id: 'painting{EntityTag:{variant:wither}}'},
{ name: 'Картина - Вода', id: 'painting{EntityTag:{variant:water}}'},
{ name: 'Картина - Встреча', id: 'painting{EntityTag:{variant:courbet}}'},
{ name: 'Картина - Грэм', id: 'painting{EntityTag:{variant:graham}}'},
{ name: 'Картина - Закат', id: 'painting{EntityTag:{variant:sunset}}'},
{ name: 'Картина - Земля', id: 'painting{EntityTag:{variant:earth}}'},
{ name: 'Картина - Конг', id: 'painting{EntityTag:{variant:donkey_kong}}'},
{ name: 'Картина - Крибережье', id: 'painting{EntityTag:{variant:creebet}}'},
{ name: 'Картина - Мятежная бренность', id: 'painting{EntityTag:{variant:skeleton}}'},
{ name: 'Картина - Наедине со свинкой', id: 'painting{EntityTag:{variant:pigscene}}'},
{ name: 'Картина - Ничто', id: 'painting{EntityTag:{variant:void}}'},
{ name: 'Картина - Огонь', id: 'painting{EntityTag:{variant:fire}}'},
{ name: 'Картина - Побережье', id: 'painting{EntityTag:{variant:sea}}'},
{ name: 'Картина - Пустошь', id: 'painting{EntityTag:{variant:wasteland}}'},
{ name: 'Картина - Пылающий череп', id: 'painting{EntityTag:{variant:burning_skull}}'},
{ name: 'Картина - Райские деревца', id: 'painting{EntityTag:{variant:plant}}'},
{ name: 'Картина - Случайный вариант', id: 'painting'},
{ name: 'Картина - Спичка', id: 'painting{EntityTag:{variant:match}}'},
{ name: 'Картина - Странник', id: 'painting{EntityTag:{variant:wanderer}}'},
{ name: 'Картина - Схватка', id: 'painting{EntityTag:{variant:fighters}}'},
{ name: 'Картина - Сцена подготовлена', id: 'painting{EntityTag:{variant:stage}}'},
{ name: 'Картина - Указатель', id: 'painting{EntityTag:{variant:pointer}}'},
{ name: 'Картина - Цель была успешно взорвана', id: 'painting{EntityTag:{variant:bomb}}'},
{ name: 'Картина - Череп и розы', id: 'painting{EntityTag:{variant:skull_and_roses}}'},
{ name: 'Картина - Шаурма, да три колбаски', id: 'painting{EntityTag:{variant:kebab}}'},
{ name: 'Картофель', id: 'potato'},
{ name: 'Кафедра', id: 'lectern'},
{ name: 'Кварцевая колонна', id: 'quartz_pillar'},
{ name: 'Кварцевая плита', id: 'quartz_slab'},
{ name: 'Кварцевые кирпичи', id: 'quartz_bricks'},
{ name: 'Кварцевые ступеньки', id: 'quartz_stairs'},
{ name: 'Кварцевый блок', id: 'quartz_block'},
{ name: 'Кирпич', id: 'brick'},
{ name: 'Кирпичи', id: 'bricks'},
{ name: 'Кирпичная ограда', id: 'brick_wall'},
{ name: 'Кирпичная плита', id: 'brick_slab'},
{ name: 'Кирпичные ступеньки', id: 'brick_stairs'},
{ name: 'Кисть', id: 'brush'},
{ name: 'Книга', id: 'book'},
{ name: 'Книга знаний', id: 'knowledge_book'},
{ name: 'Книга и перо', id: 'writable_book'},
{ name: 'Книжная полка', id: 'bookshelf'},
{ name: 'Кнопка из полированного чернита', id: 'polished_blackstone_button'},
{ name: 'Кнопка из тропического дерева', id: 'jungle_button'},
{ name: 'Кнопка из тёмного дуба', id: 'dark_oak_button'},
{ name: 'Кожа', id: 'leather'},
{ name: 'Кожаная конская броня', id: 'leather_horse_armor'},
{ name: 'Кожаная куртка', id: 'leather_chestplate'},
{ name: 'Кожаные ботинки', id: 'leather_boots'},
{ name: 'Кожаные штаны', id: 'leather_leggings'},
{ name: 'Кожаный шлем', id: 'leather_helmet'},
{ name: 'Козий рог Воспевание', id: 'goat_horn{instrument:sing_goat_horn}'},
{ name: 'Козий рог Восторг', id: 'goat_horn{instrument:admire_goat_horn}'},
{ name: 'Козий рог Зов', id: 'goat_horn{instrument:call_goat_horn}'},
{ name: 'Козий рог Мечта', id: 'goat_horn{instrument:dream_goat_horn}'},
{ name: 'Козий рог Размышление', id: 'goat_horn{instrument:ponder_goat_horn}'},
{ name: 'Козий рог Стремление', id: 'goat_horn{instrument:seek_goat_horn}'},
{ name: 'Козий рог Тоска', id: 'goat_horn{instrument:yearn_goat_horn}'},
{ name: 'Козий рог Чувство', id: 'goat_horn{instrument:feel_goat_horn}'},
{ name: 'Койф', id: 'chainmail_helmet'},
{ name: 'Колокол', id: 'bell'},
{ name: 'Колотый глубинный сланец', id: 'cobbled_deepslate'},
{ name: 'Кольчуга', id: 'chainmail_chestplate'},
{ name: 'Кольчужные ботинки', id: 'chainmail_boots'},
{ name: 'Кольчужные поножи', id: 'chainmail_leggings'},
{ name: 'Командный блок', id: 'command_block'},
{ name: 'Комок глины', id: 'clay_ball'},
{ name: 'Компас', id: 'compass'},
{ name: 'Компостница', id: 'composter'},
{ name: 'Коптильня', id: 'smoker'},
{ name: 'Коралл-мозговик', id: 'brain_coral'},
{ name: 'Коричневая глазурованная керамика', id: 'brown_glazed_terracotta'},
{ name: 'Коричневая керамика', id: 'brown_terracotta'},
{ name: 'Коричневая кровать', id: 'brown_bed'},
{ name: 'Коричневая свеча', id: 'brown_candle'},
{ name: 'Коричневая стеклянная панель', id: 'brown_stained_glass_pane'},
{ name: 'Коричневая шерсть', id: 'brown_wool'},
{ name: 'Коричневое стекло', id: 'brown_stained_glass'},
{ name: 'Коричневый бетон', id: 'brown_concrete'},
{ name: 'Коричневый гриб', id: 'brown_mushroom'},
{ name: 'Коричневый ковёр', id: 'brown_carpet'},
{ name: 'Коричневый краситель', id: 'brown_dye'},
{ name: 'Коричневый сухой бетон', id: 'brown_concrete_powder'},
{ name: 'Коричневый флаг', id: 'brown_banner'},
{ name: 'Коричневый шалкеровый ящик', id: 'brown_shulker_box'},
{ name: 'Корнистая земля', id: 'rooted_dirt'},
{ name: 'Костная мука', id: 'bone_meal'},
{ name: 'Костный блок', id: 'bone_block'},
{ name: 'Кость', id: 'bone'},
{ name: 'Костёр', id: 'campfire'},
{ name: 'Костёр душ', id: 'soul_campfire'},
{ name: 'Котёл', id: 'cauldron'},
{ name: 'Красная глазурованная керамика', id: 'red_glazed_terracotta'},
{ name: 'Красная керамика', id: 'red_terracotta'},
{ name: 'Красная кровать', id: 'red_bed'},
{ name: 'Красная свеча', id: 'red_candle'},
{ name: 'Красная стеклянная панель', id: 'red_stained_glass_pane'},
{ name: 'Красная шерсть', id: 'red_wool'},
{ name: 'Красное стекло', id: 'red_stained_glass'},
{ name: 'Красные незерские кирпичи', id: 'red_nether_bricks'},
{ name: 'Красный бетон', id: 'red_concrete'},
{ name: 'Красный гриб', id: 'red_mushroom'},
{ name: 'Красный ковёр', id: 'red_carpet'},
{ name: 'Красный краситель', id: 'red_dye'},
{ name: 'Красный песок', id: 'red_sand'},
{ name: 'Красный песчаник', id: 'red_sandstone'},
{ name: 'Красный сухой бетон', id: 'red_concrete_powder'},
{ name: 'Красный тюльпан', id: 'red_tulip'},
{ name: 'Красный флаг', id: 'red_banner'},
{ name: 'Красный шалкеровый ящик', id: 'red_shulker_box'},
{ name: 'Кремень', id: 'flint'},
{ name: 'Кристалл призмарина', id: 'prismarine_crystals'},
{ name: 'Кристалл Энда', id: 'end_crystal'},
{ name: 'Кроличья лапка', id: 'rabbit_foot'},
{ name: 'Кроличья шкурка', id: 'rabbit_hide'},
{ name: 'Крюк', id: 'tripwire_hook'},
{ name: 'Кувшинка', id: 'lily_pad'},
{ name: 'Кувшинница', id: 'pitcher_plant'},
{ name: 'Кузнечный шаблон - Незеритовое улучшение', id: 'netherite_upgrade_smithing_template'},
{ name: 'Кузнечный шаблон - Отделка Берег', id: 'coast_armor_trim_smithing_template'},
{ name: 'Кузнечный шаблон - Отделка Вождь', id: 'host_armor_trim_smithing_template'},
{ name: 'Кузнечный шаблон - Отделка Вредина', id: 'vex_armor_trim_smithing_template'},
{ name: 'Кузнечный шаблон - Отделка Дебри', id: 'wild_armor_trim_smithing_template'},
{ name: 'Кузнечный шаблон - Отделка Дюна', id: 'dune_armor_trim_smithing_template'},
{ name: 'Кузнечный шаблон - Отделка Искатель', id: 'wayfinder_armor_trim_smithing_template'},
{ name: 'Кузнечный шаблон - Отделка Око', id: 'eye_armor_trim_smithing_template'},
{ name: 'Кузнечный шаблон - Отделка Прилив', id: 'tide_armor_trim_smithing_template'},
{ name: 'Кузнечный шаблон - Отделка Ребро', id: 'rib_armor_trim_smithing_template'},
{ name: 'Кузнечный шаблон - Отделка Рыло', id: 'snout_armor_trim_smithing_template'},
{ name: 'Кузнечный шаблон - Отделка Сборщик', id: 'raiser_armor_trim_smithing_template'},
{ name: 'Кузнечный шаблон - Отделка Скульптор', id: 'shaper_armor_trim_smithing_template'},
{ name: 'Кузнечный шаблон - Отделка Страж', id: 'sentry_armor_trim_smithing_template'},
{ name: 'Кузнечный шаблон - Отделка Тишина', id: 'silence_armor_trim_smithing_template'},
{ name: 'Кузнечный шаблон - Отделка Хранитель', id: 'ward_armor_trim_smithing_template'},
{ name: 'Кузнечный шаблон - Отделка Шпиль', id: 'spire_armor_trim_smithing_template'},
{ name: 'Курятина', id: 'chicken'},
{ name: 'Кусочек железа', id: 'iron_nugget'},
{ name: 'Кусочек золота', id: 'gold_nugget'},
{ name: 'Лазурит', id: 'lapis_lazuli'},
{ name: 'Лазуритовая руда', id: 'lapis_ore'},
{ name: 'Лазуритовый блок', id: 'lapis_block'},
{ name: 'Лазуритоносный глубинный сланец', id: 'deepslate_lapis_ore'},
{ name: 'Лаймовая глазурованная керамика', id: 'lime_glazed_terracotta'},
{ name: 'Лаймовая керамика', id: 'lime_terracotta'},
{ name: 'Лаймовая кровать', id: 'lime_bed'},
{ name: 'Лаймовая свеча', id: 'lime_candle'},
{ name: 'Лаймовая стеклянная панель', id: 'lime_stained_glass_pane'},
{ name: 'Лаймовая шерсть', id: 'lime_wool'},
{ name: 'Лаймовое стекло', id: 'lime_stained_glass'},
{ name: 'Лаймовый бетон', id: 'lime_concrete'},
{ name: 'Лаймовый ковёр', id: 'lime_carpet'},
{ name: 'Лаймовый краситель', id: 'lime_dye'},
{ name: 'Лаймовый сухой бетон', id: 'lime_concrete_powder'},
{ name: 'Лаймовый флаг', id: 'lime_banner'},
{ name: 'Лаймовый шалкеровый ящик', id: 'lime_shulker_box'},
{ name: 'Ламинария', id: 'kelp'},
{ name: 'Ландыш', id: 'lily_of_the_valley'},
{ name: 'Лестница', id: 'ladder'},
{ name: 'Лианы', id: 'vine'},
{ name: 'Липкий поршень', id: 'sticky_piston'},
{ name: 'Листья азалии', id: 'azalea_leaves'},
{ name: 'Листья акации', id: 'acacia_leaves'},
{ name: 'Листья тропического дерева', id: 'jungle_leaves'},
{ name: 'Листья тёмного дуба', id: 'dark_oak_leaves'},
{ name: 'Листья цветущей азалии', id: 'flowering_azalea_leaves'},
{ name: 'Лодка из тропического дерева', id: 'jungle_boat'},
{ name: 'Лодка из тёмного дуба', id: 'dark_oak_boat'},
{ name: 'Ломтик арбуза', id: 'melon_slice'},
{ name: 'Лосось в ведре', id: 'salmon_bucket'},
{ name: 'Лук', id: 'bow'},
{ name: 'Лук-батун', id: 'allium'},
{ name: 'Люк из тропического дерева', id: 'jungle_trapdoor'},
{ name: 'Люк из тёмного дуба', id: 'dark_oak_trapdoor'},
{ name: 'Лягушачья икра', id: 'frogspawn'},
{ name: 'Лёд', id: 'ice'},
{ name: 'Магма', id: 'magma_block'},
{ name: 'Магнетит', id: 'lodestone'},
{ name: 'Мак', id: 'poppy'},
{ name: 'Малахитовая квампа', id: 'verdant_froglight'},
{ name: 'Маленькая бросянка', id: 'small_dripleaf'},
{ name: 'Малый аметистовый бутон', id: 'small_amethyst_bud'},
{ name: 'Мангровая грузовая лодка', id: 'mangrove_chest_boat'},
{ name: 'Мангровая дверь', id: 'mangrove_door'},
{ name: 'Мангровая калитка', id: 'mangrove_fence_gate'},
{ name: 'Мангровая кнопка', id: 'mangrove_button'},
{ name: 'Мангровая лодка', id: 'mangrove_boat'},
{ name: 'Мангровая нажимная плита', id: 'mangrove_pressure_plate'},
{ name: 'Мангровая плита', id: 'mangrove_slab'},
{ name: 'Мангровая подвесная табличка', id: 'mangrove_hanging_sign'},
{ name: 'Мангровая табличка', id: 'mangrove_sign'},
{ name: 'Мангровое бревно', id: 'mangrove_log'},
{ name: 'Мангровое дерево', id: 'mangrove_wood'},
{ name: 'Мангровые доски', id: 'mangrove_planks'},
{ name: 'Мангровые корни', id: 'mangrove_roots'},
{ name: 'Мангровые листья', id: 'mangrove_leaves'},
{ name: 'Мангровые ступеньки', id: 'mangrove_stairs'},
{ name: 'Мангровый забор', id: 'mangrove_fence'},
{ name: 'Мангровый люк', id: 'mangrove_trapdoor'},
{ name: 'Мангровый отросток', id: 'mangrove_propagule'},
{ name: 'Маринованный паучий глаз', id: 'fermented_spider_eye'},
{ name: 'Маяк', id: 'beacon'},
{ name: 'Меденосный глубинный сланец', id: 'deepslate_copper_ore'},
{ name: 'Медная руда', id: 'copper_ore'},
{ name: 'Медный блок', id: 'copper_block'},
{ name: 'Медный слиток', id: 'copper_ingot'},
{ name: 'Мембрана фантома', id: 'phantom_membrane'},
{ name: 'Мешок', id: 'bundle'},
{ name: 'Миска', id: 'bowl'},
{ name: 'Мицелий', id: 'mycelium'},
{ name: 'Мишень', id: 'target'},
{ name: 'Мокрая губка', id: 'wet_sponge'},
{ name: 'Морковь', id: 'carrot'},
{ name: 'Морская трава', id: 'seagrass'},
{ name: 'Морской источник', id: 'conduit'},
{ name: 'Морской огурец', id: 'sea_pickle'},
{ name: 'Морской фонарь', id: 'sea_lantern'},
{ name: 'Моховой ковёр', id: 'moss_carpet'},
{ name: 'Мутное взрывное зелье', id: 'splash_potion{Potion:awkward}'},
{ name: 'Мутное зелье', id: 'potion{Potion:awkward}'},
{ name: 'Мутное туманное зелье', id: 'lingering_potion{Potion:awkward}'},
{ name: 'Мёртвый веерный коралл-мозговик', id: 'dead_brain_coral_fan'},
{ name: 'Мёртвый веерный огненный коралл', id: 'dead_fire_coral_fan'},
{ name: 'Мёртвый веерный пузырчатый коралл', id: 'dead_bubble_coral_fan'},
{ name: 'Мёртвый веерный роговый коралл', id: 'dead_horn_coral_fan'},
{ name: 'Мёртвый веерный трубчатый коралл', id: 'dead_tube_coral_fan'},
{ name: 'Мёртвый коралл-мозговик', id: 'dead_brain_coral'},
{ name: 'Мёртвый куст', id: 'dead_bush'},
{ name: 'Мёртвый огненный коралл', id: 'dead_fire_coral'},
{ name: 'Мёртвый пузырчатый коралл', id: 'dead_bubble_coral'},
{ name: 'Мёртвый роговый коралл', id: 'dead_horn_coral'},
{ name: 'Мёртвый трубчатый коралл', id: 'dead_tube_coral'},
{ name: 'Наблюдатель', id: 'observer'},
{ name: 'Нажимная плита из полированного чернита', id: 'polished_blackstone_pressure_plate'},
{ name: 'Нажимная плита из тропического дерева', id: 'jungle_pressure_plate'},
{ name: 'Нажимная плита из тёмного дуба', id: 'dark_oak_pressure_plate'},
{ name: 'Наковальня', id: 'anvil'},
{ name: 'Натёчный камень', id: 'dripstone_block'},
{ name: 'Незер-кварц', id: 'quartz'},
{ name: 'Незер-кварцевая руда', id: 'nether_quartz_ore'},
{ name: 'Незерак', id: 'netherrack'},
{ name: 'Незеритовая кирка', id: 'netherite_pickaxe'},
{ name: 'Незеритовая лопата', id: 'netherite_shovel'},
{ name: 'Незеритовая мотыга', id: 'netherite_hoe'},
{ name: 'Незеритовые ботинки', id: 'netherite_boots'},
{ name: 'Незеритовые поножи', id: 'netherite_leggings'},
{ name: 'Незеритовый блок', id: 'netherite_block'},
{ name: 'Незеритовый лом', id: 'netherite_scrap'},
{ name: 'Незеритовый меч', id: 'netherite_sword'},
{ name: 'Незеритовый нагрудник', id: 'netherite_chestplate'},
{ name: 'Незеритовый слиток', id: 'netherite_ingot'},
{ name: 'Незеритовый топор', id: 'netherite_axe'},
{ name: 'Незеритовый шлем', id: 'netherite_helmet'},
{ name: 'Незерская золотая руда', id: 'nether_gold_ore'},
{ name: 'Незерские кирпичи', id: 'nether_bricks'},
{ name: 'Незерские ростки', id: 'nether_sprouts'},
{ name: 'Незерский кирпич', id: 'nether_brick'},
{ name: 'Незерский нарост', id: 'nether_wart'},
{ name: 'Нить', id: 'string'},
{ name: 'Ножка гриба', id: 'mushroom_stem'},
{ name: 'Ножницы', id: 'shears'},
{ name: 'Нотный блок', id: 'note_block'},
{ name: 'Обработанная стрела 1', id: 'tipped_arrow{Potion:mundane}'},
{ name: 'Обработанная стрела 2', id: 'tipped_arrow{Potion:thick}'},
{ name: 'Обработанная стрела 3', id: 'tipped_arrow{Potion:awkward}'},
{ name: 'Обсидиан', id: 'obsidian'},
{ name: 'Обтёсанная акациевая древесина', id: 'stripped_acacia_wood'},
{ name: 'Обтёсанная берёзовая древесина', id: 'stripped_birch_wood'},
{ name: 'Обтёсанная вишневая древесина', id: 'stripped_cherry_wood'},
{ name: 'Обтёсанная древесина тёмного дуба', id: 'stripped_dark_oak_wood'},
{ name: 'Обтёсанная дубовая древесина', id: 'stripped_oak_wood'},
{ name: 'Обтёсанная еловая древесина', id: 'stripped_spruce_wood'},
{ name: 'Обтёсанная мангровая древесина', id: 'stripped_mangrove_wood'},
{ name: 'Обтёсанная тропическая древесина', id: 'stripped_jungle_wood'},
{ name: 'Обтёсанное акациевое бревно', id: 'stripped_acacia_log'},
{ name: 'Обтёсанное берёзовое бревно', id: 'stripped_birch_log'},
{ name: 'Обтёсанное бревно тропического дерева', id: 'stripped_jungle_log'},
{ name: 'Обтёсанное бревно тёмного дуба', id: 'stripped_dark_oak_log'},
{ name: 'Обтёсанное вишнёвое бревно', id: 'stripped_cherry_log'},
{ name: 'Обтёсанное дубовое бревно', id: 'stripped_oak_log'},
{ name: 'Обтёсанное еловое бревно', id: 'stripped_spruce_log'},
{ name: 'Обтёсанное мангровое бревно', id: 'stripped_mangrove_log'},
{ name: 'Огненный заряд', id: 'fire_charge'},
{ name: 'Огненный коралл', id: 'fire_coral'},
{ name: 'Огненный порошок', id: 'blaze_powder'},
{ name: 'Огненный стержень', id: 'blaze_rod'},
{ name: 'Огниво', id: 'flint_and_steel'},
{ name: 'Ограда из глубинносланцевого кирпича', id: 'deepslate_brick_wall'},
{ name: 'Ограда из глубинносланцевого плитняка', id: 'deepslate_tile_wall'},
{ name: 'Ограда из замшелого каменного кирпича', id: 'mossy_stone_brick_wall'},
{ name: 'Ограда из каменного кирпича', id: 'stone_brick_wall'},
{ name: 'Ограда из колотого глубинного сланца', id: 'cobbled_deepslate_wall'},
{ name: 'Ограда из красного незерского кирпича', id: 'red_nether_brick_wall'},
{ name: 'Ограда из красного песчаника', id: 'red_sandstone_wall'},
{ name: 'Ограда из незерского кирпича', id: 'nether_brick_wall'},
{ name: 'Ограда из полированно-чернитного кирпича', id: 'polished_blackstone_brick_wall'},
{ name: 'Ограда из полированного глубинного сланца', id: 'polished_deepslate_wall'},
{ name: 'Ограда из полированного чернита', id: 'polished_blackstone_wall'},
{ name: 'Ограда из эндернякового кирпича', id: 'end_stone_brick_wall'},
{ name: 'Одуванчик', id: 'dandelion'},
{ name: 'Окаменевшая дубовая плита', id: 'petrified_oak_slab'},
{ name: 'Окисленная резная медная плита', id: 'oxidized_cut_copper_slab'},
{ name: 'Окисленные резные медные ступеньки', id: 'oxidized_cut_copper_stairs'},
{ name: 'Окисленный медный блок', id: 'oxidized_copper'},
{ name: 'Окисленный резной медный блок', id: 'oxidized_cut_copper'},
{ name: 'Око Эндера', id: 'ender_eye'},
{ name: 'Оранжевая глазурованная керамика', id: 'orange_glazed_terracotta'},
{ name: 'Оранжевая керамика', id: 'orange_terracotta'},
{ name: 'Оранжевая кровать', id: 'orange_bed'},
{ name: 'Оранжевая свеча', id: 'orange_candle'},
{ name: 'Оранжевая стеклянная панель', id: 'orange_stained_glass_pane'},
{ name: 'Оранжевая шерсть', id: 'orange_wool'},
{ name: 'Оранжевое стекло', id: 'orange_stained_glass'},
{ name: 'Оранжевый бетон', id: 'orange_concrete'},
{ name: 'Оранжевый ковёр', id: 'orange_carpet'},
{ name: 'Оранжевый краситель', id: 'orange_dye'},
{ name: 'Оранжевый сухой бетон', id: 'orange_concrete_powder'},
{ name: 'Оранжевый тюльпан', id: 'orange_tulip'},
{ name: 'Оранжевый флаг', id: 'orange_banner'},
{ name: 'Оранжевый шалкеровый ящик', id: 'orange_shulker_box'},
{ name: 'Осколок аметиста', id: 'amethyst_shard'},
{ name: 'Осколок пластинки', id: 'disc_fragment_5'},
{ name: 'Осколок призмарина', id: 'prismarine_shard'},
{ name: 'Осколок эха', id: 'echo_shard'},
{ name: 'Откалиброванный скалк-сенсор', id: 'calibrated_sculk_sensor'},
{ name: 'Охристая квампа', id: 'ochre_froglight'},
{ name: 'Очищенные багровые гифы', id: 'stripped_crimson_hyphae'},
{ name: 'Очищенные искажённые гифы', id: 'stripped_warped_hyphae'},
{ name: 'Очищенный багровый стебель', id: 'stripped_crimson_stem'},
{ name: 'Очищенный искажённый стебель', id: 'stripped_warped_stem'},
{ name: 'Пазл', id: 'jigsaw'},
{ name: 'Палка', id: 'stick'},
{ name: 'Палочка отладки', id: 'debug_stick'},
{ name: 'Панцирь шалкера', id: 'shulker_shell'},
{ name: 'Папоротник', id: 'fern'},
{ name: 'Паутина', id: 'cobweb'},
{ name: 'Паучий глаз', id: 'spider_eye'},
{ name: 'Пашня', id: 'farmland'},
{ name: 'Перламутровая квампа', id: 'pearlescent_froglight'},
{ name: 'Перо', id: 'feather'},
{ name: 'Песок', id: 'sand'},
{ name: 'Песок душ', id: 'soul_sand'},
{ name: 'Песчаник', id: 'sandstone'},
{ name: 'Песчаниковая ограда', id: 'sandstone_wall'},
{ name: 'Песчаниковая плита', id: 'sandstone_slab'},
{ name: 'Песчаниковые ступеньки', id: 'sandstone_stairs'},
{ name: 'Печенье', id: 'cookie'},
{ name: 'Печь', id: 'furnace'},
{ name: 'Печёный картофель', id: 'baked_potato'},
{ name: 'Пиленый красный песчаник', id: 'cut_red_sandstone'},
{ name: 'Пиленый песчаник', id: 'cut_sandstone'},
{ name: 'Пион', id: 'peony'},
{ name: 'Пиротехническая звезда', id: 'firework_star'},
{ name: 'Плавильная печь', id: 'blast_furnace'},
{ name: 'Плакучая лоза', id: 'weeping_vines'},
{ name: 'Пластинка C-418 - 13', id: 'music_disc_13'},
{ name: 'Пластинка C-418 - Блоки', id: 'music_disc_blocks'},
{ name: 'Пластинка C-418 - Даль', id: 'music_disc_far'},
{ name: 'Пластинка C-418 - Кот', id: 'music_disc_cat'},
{ name: 'Пластинка C-418 - Меллохи', id: 'music_disc_mellohi'},
{ name: 'Пластинка C-418 - Ожидание', id: 'music_disc_wait'},
{ name: 'Пластинка C-418 - Стал', id: 'music_disc_stal'},
{ name: 'Пластинка C-418 - Сторож', id: 'music_disc_ward'},
{ name: 'Пластинка C-418 - Торговый центр', id: 'music_disc_mall'},
{ name: 'Пластинка C-418 - Улица', id: 'music_disc_strad'},
{ name: 'Пластинка C-418 - Чириканье', id: 'music_disc_chirp'},
{ name: 'Пластинка Лена Рейн - Другая сторона', id: 'music_disc_otherside'},
{ name: 'Пластинка Лена Рейн - Свинья', id: 'music_disc_pigstep'},
{ name: 'Пластинка Самуель Оберг - 5', id: 'music_disc_5'},
{ name: 'Пластинкка - Relic', id: 'music_disc_relic'},
{ name: 'Плачущий обсидиан', id: 'crying_obsidian'},
{ name: 'Плита из бамбуковой мозаики', id: 'bamboo_mosaic_slab'},
{ name: 'Плита из гладкого камня', id: 'smooth_stone_slab'},
{ name: 'Плита из гладкого кварца', id: 'smooth_quartz_slab'},
{ name: 'Плита из гладкого красного песчаника', id: 'smooth_red_sandstone_slab'},
{ name: 'Плита из гладкого песчаника', id: 'smooth_sandstone_slab'},
{ name: 'Плита из глубинносланцевого кирпича', id: 'deepslate_brick_slab'},
{ name: 'Плита из глубинносланцевого плитняка', id: 'deepslate_tile_slab'},
{ name: 'Плита из замшелого каменного кирпича', id: 'mossy_stone_brick_slab'},
{ name: 'Плита из каменного кирпича', id: 'stone_brick_slab'},
{ name: 'Плита из колотого глубинного сланца', id: 'cobbled_deepslate_slab'},
{ name: 'Плита из красного незерского кирпича', id: 'red_nether_brick_slab'},
{ name: 'Плита из красного песчаника', id: 'red_sandstone_slab'},
{ name: 'Плита из незерского кирпича', id: 'nether_brick_slab'},
{ name: 'Плита из пиленого красного песчаника', id: 'cut_red_sandstone_slab'},
{ name: 'Плита из пиленого песчаника', id: 'cut_sandstone_slab'},
{ name: 'Плита из полированно-чернитного кирпича', id: 'polished_blackstone_brick_slab'},
{ name: 'Плита из полированного андезита', id: 'polished_andesite_slab'},
{ name: 'Плита из полированного глубинного сланца', id: 'polished_deepslate_slab'},
{ name: 'Плита из полированного гранита', id: 'polished_granite_slab'},
{ name: 'Плита из полированного диорита', id: 'polished_diorite_slab'},
{ name: 'Плита из полированного чернита', id: 'polished_blackstone_slab'},
{ name: 'Плита из призмаринового кирпича', id: 'prismarine_brick_slab'},
{ name: 'Плита из тропического дерева', id: 'jungle_slab'},
{ name: 'Плита из тёмного дуба', id: 'dark_oak_slab'},
{ name: 'Плита из тёмного призмарина', id: 'dark_prismarine_slab'},
{ name: 'Плита из эндернякового кирпича', id: 'end_stone_brick_slab'},
{ name: 'Плод хоруса', id: 'chorus_fruit'},
{ name: 'Плотная грязь', id: 'packed_mud'},
{ name: 'Плотный лёд', id: 'packed_ice'},
{ name: 'Поводок', id: 'lead'},
{ name: 'Повреждённая наковальня', id: 'chipped_anvil'},
{ name: 'Повторяющий командный блок', id: 'repeating_command_block'},
{ name: 'Подвесная табличка из тропического дерева', id: 'jungle_hanging_sign'},
{ name: 'Подвесная табличка из тёмного дуба', id: 'dark_oak_hanging_sign'},
{ name: 'Подзол', id: 'podzol'},
{ name: 'Подзорная труба', id: 'spyglass'},
{ name: 'Подмостки', id: 'scaffolding'},
{ name: 'Подозрительный гравий', id: 'suspicious_gravel'},
{ name: 'Подозрительный песок', id: 'suspicious_sand'},
{ name: 'Подсолнух', id: 'sunflower'},
{ name: 'Полированно-чернитные кирпичи', id: 'polished_blackstone_bricks'},
{ name: 'Полированный андезит', id: 'polished_andesite'},
{ name: 'Полированный базальт', id: 'polished_basalt'},
{ name: 'Полированный глубинный сланец', id: 'polished_deepslate'},
{ name: 'Полированный гранит', id: 'polished_granite'},
{ name: 'Полированный диорит', id: 'polished_diorite'},
{ name: 'Полированный чернит', id: 'polished_blackstone'},
{ name: 'Порох', id: 'gunpowder'},
{ name: 'Поршень', id: 'piston'},
{ name: 'Последовательный командный блок', id: 'chain_command_block'},
{ name: 'Потемневшая резная медная плита', id: 'exposed_cut_copper_slab'},
{ name: 'Потемневшие резные медные ступеньки', id: 'exposed_cut_copper_stairs'},
{ name: 'Потемневший медный блок', id: 'exposed_copper'},
{ name: 'Потемневший резной медный блок', id: 'exposed_cut_copper'},
{ name: 'Потрескавшиеся глубинносланцевые кирпичи', id: 'cracked_deepslate_bricks'},
{ name: 'Потрескавшиеся каменные кирпичи', id: 'cracked_stone_bricks'},
{ name: 'Потрескавшиеся незерские кирпичи', id: 'cracked_nether_bricks'},
{ name: 'Потрескавшиеся полированно-чернитные кирпичи', id: 'cracked_polished_blackstone_bricks'},
{ name: 'Потрескавшийся глубинносланцевый плитняк', id: 'cracked_deepslate_tiles'},
{ name: 'Почва душ', id: 'soul_soil'},
{ name: 'Призмарин', id: 'prismarine'},
{ name: 'Призмариновая ограда', id: 'prismarine_wall'},
{ name: 'Призмариновая плита', id: 'prismarine_slab'},
{ name: 'Призмариновые кирпичи', id: 'prismarine_bricks'},
{ name: 'Призмариновые ступеньки', id: 'prismarine_stairs'},
{ name: 'Прожаренный плод хоруса', id: 'popped_chorus_fruit'},
{ name: 'Проигрыватель', id: 'jukebox'},
{ name: 'Пузырчатый коралл', id: 'bubble_coral'},
{ name: 'Пузырёк опыта', id: 'experience_bottle'},
{ name: 'Пурпур', id: 'purpur_block'},
{ name: 'Пурпурная глазурованная керамика', id: 'magenta_glazed_terracotta'},
{ name: 'Пурпурная керамика', id: 'magenta_terracotta'},
{ name: 'Пурпурная кровать', id: 'magenta_bed'},
{ name: 'Пурпурная свеча', id: 'magenta_candle'},
{ name: 'Пурпурная стеклянная панель', id: 'magenta_stained_glass_pane'},
{ name: 'Пурпурная шерсть', id: 'magenta_wool'},
{ name: 'Пурпурное стекло', id: 'magenta_stained_glass'},
{ name: 'Пурпурный бетон', id: 'magenta_concrete'},
{ name: 'Пурпурный ковёр', id: 'magenta_carpet'},
{ name: 'Пурпурный краситель', id: 'magenta_dye'},
{ name: 'Пурпурный сухой бетон', id: 'magenta_concrete_powder'},
{ name: 'Пурпурный флаг', id: 'magenta_banner'},
{ name: 'Пурпурный шалкеровый ящик', id: 'magenta_shulker_box'},
{ name: 'Пурпуровая плита', id: 'purpur_slab'},
{ name: 'Пурпуровые ступеньки', id: 'purpur_stairs'},
{ name: 'Пурпуровый пилон', id: 'purpur_pillar'},
{ name: 'Пустой блок', id: 'structure_void'},
{ name: 'Пчелиное гнездо', id: 'bee_nest'},
{ name: 'Пчелиные соты', id: 'honeycomb'},
{ name: 'Пшеница', id: 'wheat'},
{ name: 'Разбитая наковальня', id: 'damaged_anvil'},
{ name: 'Раздатчик', id: 'dispenser'},
{ name: 'Раковина наутилуса', id: 'nautilus_shell'},
{ name: 'Рамка', id: 'item_frame'},
{ name: 'Рамка портала в Энд', id: 'end_portal_frame'},
{ name: 'Раскидистый папоротник', id: 'large_fern'},
{ name: 'Рассадник монстров', id: 'spawner'},
{ name: 'Редстоуновая пыль', id: 'redstone'},
{ name: 'Редстоуновая руда', id: 'redstone_ore'},
{ name: 'Редстоуновый блок', id: 'redstone_block'},
{ name: 'Редстоуновый компаратор', id: 'comparator'},
{ name: 'Редстоуновый повторитель', id: 'repeater'},
{ name: 'Редстоуновый факел', id: 'redstone_torch'},
{ name: 'Редстоуновый фонарь', id: 'redstone_lamp'},
{ name: 'Редстоуноносный глубинный сланец', id: 'deepslate_redstone_ore'},
{ name: 'Резная книжная полка', id: 'chiseled_bookshelf'},
{ name: 'Резная медная плита', id: 'cut_copper_slab'},
{ name: 'Резной глубинный сланец', id: 'chiseled_deepslate'},
{ name: 'Резной кварцевый блок', id: 'chiseled_quartz_block'},
{ name: 'Резной красный песчаник', id: 'chiseled_red_sandstone'},
{ name: 'Резной медный блок', id: 'cut_copper'},
{ name: 'Резной песчаник', id: 'chiseled_sandstone'},
{ name: 'Резной полированный чернит', id: 'chiseled_polished_blackstone'},
{ name: 'Резные каменные кирпичи', id: 'chiseled_stone_bricks'},
{ name: 'Резные медные ступеньки', id: 'cut_copper_stairs'},
{ name: 'Резные незерские кирпичи', id: 'chiseled_nether_bricks'},
{ name: 'Рельсы', id: 'rail'},
{ name: 'Рельсы с датчиком', id: 'detector_rail'},
{ name: 'Роговый коралл', id: 'horn_coral'},
{ name: 'Роза визера', id: 'wither_rose'},
{ name: 'Розовая глазурованная керамика', id: 'pink_glazed_terracotta'},
{ name: 'Розовая керамика', id: 'pink_terracotta'},
{ name: 'Розовая кровать', id: 'pink_bed'},
{ name: 'Розовая свеча', id: 'pink_candle'},
{ name: 'Розовая стеклянная панель', id: 'pink_stained_glass_pane'},
{ name: 'Розовая шерсть', id: 'pink_wool'},
{ name: 'Розовое стекло', id: 'pink_stained_glass'},
{ name: 'Розовые лепестки', id: 'pink_petals'},
{ name: 'Розовый бетон', id: 'pink_concrete'},
{ name: 'Розовый ковёр', id: 'pink_carpet'},
{ name: 'Розовый краситель', id: 'pink_dye'},
{ name: 'Розовый куст', id: 'rose_bush'},
{ name: 'Розовый сухой бетон', id: 'pink_concrete_powder'},
{ name: 'Розовый тюльпан', id: 'pink_tulip'},
{ name: 'Розовый флаг', id: 'pink_banner'},
{ name: 'Розовый шалкеровый ящик', id: 'pink_shulker_box'},
{ name: 'Ромашка', id: 'oxeye_daisy'},
{ name: 'Рудная медь', id: 'raw_copper'},
{ name: 'Рудное железо', id: 'raw_iron'},
{ name: 'Рудное золото', id: 'raw_gold'},
{ name: 'Рычаг', id: 'lever'},
{ name: 'Саженец акации', id: 'acacia_sapling'},
{ name: 'Саженец берёзы', id: 'birch_sapling'},
{ name: 'Саженец вишни', id: 'cherry_sapling'},
{ name: 'Саженец дуба', id: 'oak_sapling'},
{ name: 'Саженец ели', id: 'spruce_sapling'},
{ name: 'Саженец тропического дерева', id: 'jungle_sapling'},
{ name: 'Саженец тёмного дуба', id: 'dark_oak_sapling'},
{ name: 'Саманная ограда', id: 'mud_brick_wall'},
{ name: 'Саманная плита', id: 'mud_brick_slab'},
{ name: 'Саманные кирпичи', id: 'mud_bricks'},
{ name: 'Саманные ступеньки', id: 'mud_brick_stairs'},
{ name: 'Самоходная вагонетка', id: 'furnace_minecart'},
{ name: 'Сахар', id: 'sugar'},
{ name: 'Сахарный тростник', id: 'sugar_cane'},
{ name: 'Свекольный суп', id: 'beetroot_soup'},
{ name: 'Сверкающий ломтик арбуза', id: 'glistering_melon_slice'},
{ name: 'Свет', id: 'light'},
{ name: 'Светильник Джека', id: 'jack_o_lantern'},
{ name: 'Светло-серая глазурованная керамика', id: 'light_gray_glazed_terracotta'},
{ name: 'Светло-серая керамика', id: 'light_gray_terracotta'},
{ name: 'Светло-серая кровать', id: 'light_gray_bed'},
{ name: 'Светло-серая свеча', id: 'light_gray_candle'},
{ name: 'Светло-серая стеклянная панель', id: 'light_gray_stained_glass_pane'},
{ name: 'Светло-серая шерсть', id: 'light_gray_wool'},
{ name: 'Светло-серое стекло', id: 'light_gray_stained_glass'},
{ name: 'Светло-серый бетон', id: 'light_gray_concrete'},
{ name: 'Светло-серый ковёр', id: 'light_gray_carpet'},
{ name: 'Светло-серый краситель', id: 'light_gray_dye'},
{ name: 'Светло-серый сухой бетон', id: 'light_gray_concrete_powder'},
{ name: 'Светло-серый флаг', id: 'light_gray_banner'},
{ name: 'Светло-серый шалкеровый ящик', id: 'light_gray_shulker_box'},
{ name: 'Светокаменная пыль', id: 'glowstone_dust'},
{ name: 'Светокамень', id: 'glowstone'},
{ name: 'Светящаяся рамка', id: 'glow_item_frame'},
{ name: 'Светящиеся ягоды', id: 'glow_berries'},
{ name: 'Светящийся лишайник', id: 'glow_lichen'},
{ name: 'Светящийся чернильный мешок', id: 'glow_ink_sac'},
{ name: 'Свеча', id: 'candle'},
{ name: 'Свисающие корни', id: 'hanging_roots'},
{ name: 'Свёкла', id: 'beetroot'},
{ name: 'Сгусток магмы', id: 'magma_cream'},
{ name: 'Сгусток слизи', id: 'slime_ball'},
{ name: 'Седло', id: 'saddle'},
{ name: 'Семена арбуза', id: 'melon_seeds'},
{ name: 'Семена пшеницы', id: 'wheat_seeds'},
{ name: 'Семена свёклы', id: 'beetroot_seeds'},
{ name: 'Семена тыквы', id: 'pumpkin_seeds'},
{ name: 'Семена факельника', id: 'torchflower_seeds'},
{ name: 'Серая глазурованная керамика', id: 'gray_glazed_terracotta'},
{ name: 'Серая керамика', id: 'gray_terracotta'},
{ name: 'Серая кровать', id: 'gray_bed'},
{ name: 'Серая свеча', id: 'gray_candle'},
{ name: 'Серая стеклянная панель', id: 'gray_stained_glass_pane'},
{ name: 'Серая шерсть', id: 'gray_wool'},
{ name: 'Сердце моря', id: 'heart_of_the_sea'},
{ name: 'Серое стекло', id: 'gray_stained_glass'},
{ name: 'Серый бетон', id: 'gray_concrete'},
{ name: 'Серый ковёр', id: 'gray_carpet'},
{ name: 'Серый краситель', id: 'gray_dye'},
{ name: 'Серый сухой бетон', id: 'gray_concrete_powder'},
{ name: 'Серый флаг', id: 'gray_banner'},
{ name: 'Серый шалкеровый ящик', id: 'gray_shulker_box'},
{ name: 'Синее стекло', id: 'blue_stained_glass'},
{ name: 'Синий бетон', id: 'blue_concrete'},
{ name: 'Синий василёк', id: 'cornflower'},
{ name: 'Синий ковёр', id: 'blue_carpet'},
{ name: 'Синий краситель', id: 'blue_dye'},
{ name: 'Синий лёд', id: 'blue_ice'},
{ name: 'Синий сухой бетон', id: 'blue_concrete_powder'},
{ name: 'Синий флаг', id: 'blue_banner'},
{ name: 'Синий шалкеровый ящик', id: 'blue_shulker_box'},
{ name: 'Синяя глазурованная керамика', id: 'blue_glazed_terracotta'},
{ name: 'Синяя керамика', id: 'blue_terracotta'},
{ name: 'Синяя кровать', id: 'blue_bed'},
{ name: 'Синяя орхидея', id: 'blue_orchid'},
{ name: 'Синяя свеча', id: 'blue_candle'},
{ name: 'Синяя стеклянная панель', id: 'blue_stained_glass_pane'},
{ name: 'Синяя шерсть', id: 'blue_wool'},
{ name: 'Сирень', id: 'lilac'},
{ name: 'Скалк', id: 'sculk'},
{ name: 'Скалк-сенсор', id: 'sculk_sensor'},
{ name: 'Скалковая жила', id: 'sculk_vein'},
{ name: 'Скалковый катализатор', id: 'sculk_catalyst'},
{ name: 'Скалковый крикун', id: 'sculk_shrieker'},
{ name: 'Сладкие ягоды', id: 'sweet_berries'},
{ name: 'Слеза гаста', id: 'ghast_tear'},
{ name: 'Сломанная пластинка', id: 'music_disc_11'},
{ name: 'Снег', id: 'snow'},
{ name: 'Снежок', id: 'snowball'},
{ name: 'Сноп сена', id: 'hay_block'},
{ name: 'Состаренная резная медная плита', id: 'weathered_cut_copper_slab'},
{ name: 'Состаренные резные медные ступеньки', id: 'weathered_cut_copper_stairs'},
{ name: 'Состаренный медный блок', id: 'weathered_copper'},
{ name: 'Состаренный резной медный блок', id: 'weathered_cut_copper'},
{ name: 'Спектральная стрела', id: 'spectral_arrow'},
{ name: 'Спороцвет', id: 'spore_blossom'},
{ name: 'Средний аметистовый бутон', id: 'medium_amethyst_bud'},
{ name: 'Стейк', id: 'cooked_beef'},
{ name: 'Стекло', id: 'glass'},
{ name: 'Стеклянная панель', id: 'glass_pane'},
{ name: 'Стержень Энда', id: 'end_rod'},
{ name: 'Стойка для брони', id: 'armor_stand'},
{ name: 'Стол картографа', id: 'cartography_table'},
{ name: 'Стол кузнеца', id: 'smithing_table'},
{ name: 'Стол лучника', id: 'fletching_table'},
{ name: 'Стрела', id: 'arrow'},
{ name: 'Стрела везения', id: 'tipped_arrow{Potion:luck}'},
{ name: 'Стрела водного дыхания', id: 'tipped_arrow{Potion:water_breathing}'},
{ name: 'Стрела водного дыхания продлённая', id: 'tipped_arrow{Potion:long_water_breathing}'},
{ name: 'Стрела вреда', id: 'tipped_arrow{Potion:harming}'},
{ name: 'Стрела вреда усиленная', id: 'tipped_arrow{Potion:strong_harming}'},
{ name: 'Стрела замедления', id: 'tipped_arrow{Potion:slowness}'},
{ name: 'Стрела замедления продлённая', id: 'tipped_arrow{Potion:long_slowness}'},
{ name: 'Стрела замедления усиленная', id: 'tipped_arrow{Potion:strong_slowness}'},
{ name: 'Стрела исцеления', id: 'tipped_arrow{Potion:healing}'},
{ name: 'Стрела исцеления усиленная', id: 'tipped_arrow{Potion:strong_healing}'},
{ name: 'Стрела невидимости', id: 'tipped_arrow{Potion:invisibility}'},
{ name: 'Стрела невидимости продлённая', id: 'tipped_arrow{Potion:long_invisibility}'},
{ name: 'Стрела ночного зрения', id: 'tipped_arrow{Potion:night_vision}'},
{ name: 'Стрела ночного зрения продлённая', id: 'tipped_arrow{Potion:long_night_vision}'},
{ name: 'Стрела огнестойкости', id: 'tipped_arrow{Potion:fire_resistance}'},
{ name: 'Стрела огнестойкости продлённая', id: 'tipped_arrow{Potion:long_fire_resistance}'},
{ name: 'Стрела отравления', id: 'tipped_arrow{Potion:poison}'},
{ name: 'Стрела отравления продлённая', id: 'tipped_arrow{Potion:long_poison}'},
{ name: 'Стрела отравления усиленная', id: 'tipped_arrow{Potion:strong_poison}'},
{ name: 'Стрела плавного падения', id: 'tipped_arrow{Potion:slow_falling}'},
{ name: 'Стрела плавного падения продлённая', id: 'tipped_arrow{Potion:long_slow_falling}'},
{ name: 'Стрела прыгучести', id: 'tipped_arrow{Potion:leaping}'},
{ name: 'Стрела прыгучести продлённая', id: 'tipped_arrow{Potion:long_leaping}'},
{ name: 'Стрела прыгучести усиленная', id: 'tipped_arrow{Potion:strong_leaping}'},
{ name: 'Стрела регенерации', id: 'tipped_arrow{Potion:regeneration}'},
{ name: 'Стрела регенерации продлённая', id: 'tipped_arrow{Potion:long_regeneration}'},
{ name: 'Стрела регенерации усиленная', id: 'tipped_arrow{Potion:strong_regeneration}'},
{ name: 'Стрела силы', id: 'tipped_arrow{Potion:strength}'},
{ name: 'Стрела силы продлённая', id: 'tipped_arrow{Potion:long_strength}'},
{ name: 'Стрела силы усиленная', id: 'tipped_arrow{Potion:strong_strength}'},
{ name: 'Стрела слабости', id: 'tipped_arrow{Potion:weakness}'},
{ name: 'Стрела слабости продлённая', id: 'tipped_arrow{Potion:long_weakness}'},
{ name: 'Стрела стремительности', id: 'tipped_arrow{Potion:swiftness}'},
{ name: 'Стрела стремительности продлённая', id: 'tipped_arrow{Potion:long_swiftness}'},
{ name: 'Стрела стремительности усиленная', id: 'tipped_arrow{Potion:strong_swiftness}'},
{ name: 'Стрела черепашьей мощи', id: 'tipped_arrow{Potion:turtle_master}'},
{ name: 'Стрела черепашьей мощи продлённая', id: 'tipped_arrow{Potion:long_turtle_master}'},
{ name: 'Стрела черепашьей мощи усиленная', id: 'tipped_arrow{Potion:strong_turtle_master}'},
{ name: 'Стручок кувшинницы', id: 'pitcher_pod'},
{ name: 'Ступеньки из бамбуковой мозаики', id: 'bamboo_mosaic_stairs'},
{ name: 'Ступеньки из гладкого кварца', id: 'smooth_quartz_stairs'},
{ name: 'Ступеньки из гладкого красного песчаника', id: 'smooth_red_sandstone_stairs'},
{ name: 'Ступеньки из гладкого песчаника', id: 'smooth_sandstone_stairs'},
{ name: 'Ступеньки из глубинносланцевого кирпича', id: 'deepslate_brick_stairs'},
{ name: 'Ступеньки из глубинносланцевого плитняка', id: 'deepslate_tile_stairs'},
{ name: 'Ступеньки из замшелого каменного кирпича', id: 'mossy_stone_brick_stairs'},
{ name: 'Ступеньки из каменного кирпича', id: 'stone_brick_stairs'},
{ name: 'Ступеньки из колотого глубинного сланца', id: 'cobbled_deepslate_stairs'},
{ name: 'Ступеньки из красного незерского кирпича', id: 'red_nether_brick_stairs'},
{ name: 'Ступеньки из красного песчаника', id: 'red_sandstone_stairs'},
{ name: 'Ступеньки из незерского кирпича', id: 'nether_brick_stairs'},
{ name: 'Ступеньки из полированно-чернитного кирпича', id: 'polished_blackstone_brick_stairs'},
{ name: 'Ступеньки из полированного андезита', id: 'polished_andesite_stairs'},
{ name: 'Ступеньки из полированного глубинного сланца', id: 'polished_deepslate_stairs'},
{ name: 'Ступеньки из полированного гранита', id: 'polished_granite_stairs'},
{ name: 'Ступеньки из полированного диорита', id: 'polished_diorite_stairs'},
{ name: 'Ступеньки из полированного чернита', id: 'polished_blackstone_stairs'},
{ name: 'Ступеньки из призмаринового кирпича', id: 'prismarine_brick_stairs'},
{ name: 'Ступеньки из тропического дерева', id: 'jungle_stairs'},
{ name: 'Ступеньки из тёмного дуба', id: 'dark_oak_stairs'},
{ name: 'Ступеньки из тёмного призмарина', id: 'dark_prismarine_stairs'},
{ name: 'Ступеньки из эндернякового кирпича', id: 'end_stone_brick_stairs'},
{ name: 'Сундук', id: 'chest'},
{ name: 'Сундук-ловушка', id: 'trapped_chest'},
{ name: 'Сушёная ламинария', id: 'dried_kelp'},
{ name: 'Сырая баранина', id: 'mutton'},
{ name: 'Сырая говядина', id: 'beef'},
{ name: 'Сырая крольчатина', id: 'rabbit'},
{ name: 'Сырая свинина', id: 'porkchop'},
{ name: 'Сырая треска', id: 'cod'},
{ name: 'Сырой лосось', id: 'salmon'},
{ name: 'Табличка из тропического дерева', id: 'jungle_sign'},
{ name: 'Табличка из тёмного дуба', id: 'dark_oak_sign'},
{ name: 'Терракота', id: 'terracotta'},
{ name: 'Ткацкий станок', id: 'loom'},
{ name: 'Тонированное стекло', id: 'tinted_glass'},
{ name: 'Торт', id: 'cake'},
{ name: 'Тотем бессмертия', id: 'totem_of_undying'},
{ name: 'Точило', id: 'grindstone'},
{ name: 'Трава', id: 'grass'},
{ name: 'Трезубец', id: 'trident'},
{ name: 'Треска в ведре', id: 'cod_bucket'},
{ name: 'Тропинка', id: 'dirt_path'},
{ name: 'Тропическая рыба', id: 'tropical_fish'},
{ name: 'Тропическая рыба в ведре', id: 'tropical_fish_bucket'},
{ name: 'Тропическое дерево', id: 'jungle_wood'},
{ name: 'Трубчатый коралл', id: 'tube_coral'},
{ name: 'Туманное Зелье Везения', id: 'lingering_potion{Potion:luck}'},
{ name: 'Туманное Зелье Водного дыхания', id: 'lingering_potion{Potion:water_breathing}'},
{ name: 'Туманное Зелье Водного дыхания продлённое', id: 'lingering_potion{Potion:long_water_breathing}'},
{ name: 'Туманное Зелье Вреда', id: 'lingering_potion{Potion:harming}'},
{ name: 'Туманное Зелье Вреда усиленное', id: 'lingering_potion{Potion:strong_harming}'},
{ name: 'Туманное Зелье Замедления', id: 'lingering_potion{Potion:slowness}'},
{ name: 'Туманное Зелье Замедления продлённое', id: 'lingering_potion{Potion:long_slowness}'},
{ name: 'Туманное Зелье Замедления усиленное', id: 'lingering_potion{Potion:strong_slowness}'},
{ name: 'Туманное Зелье Исцеления', id: 'lingering_potion{Potion:healing}'},
{ name: 'Туманное Зелье Исцеления усиленное', id: 'lingering_potion{Potion:strong_healing}'},
{ name: 'Туманное Зелье Невидимости', id: 'lingering_potion{Potion:invisibility}'},
{ name: 'Туманное Зелье Невидимости продлённое', id: 'lingering_potion{Potion:long_invisibility}'},
{ name: 'Туманное Зелье Ночного зрения', id: 'lingering_potion{Potion:night_vision}'},
{ name: 'Туманное Зелье Ночного зрения продлённое', id: 'lingering_potion{Potion:long_night_vision}'},
{ name: 'Туманное Зелье Огнестойкости', id: 'lingering_potion{Potion:fire_resistance}'},
{ name: 'Туманное Зелье Огнестойкости продлённое', id: 'lingering_potion{Potion:long_fire_resistance}'},
{ name: 'Туманное Зелье Отравления', id: 'lingering_potion{Potion:poison}'},
{ name: 'Туманное Зелье Отравления продлённое', id: 'lingering_potion{Potion:long_poison}'},
{ name: 'Туманное Зелье Отравления усиленное', id: 'lingering_potion{Potion:strong_poison}'},
{ name: 'Туманное Зелье Плавного падения', id: 'lingering_potion{Potion:slow_falling}'},
{ name: 'Туманное Зелье Плавного падения продлённое', id: 'lingering_potion{Potion:long_slow_falling}'},
{ name: 'Туманное Зелье Прыгучести', id: 'lingering_potion{Potion:leaping}'},
{ name: 'Туманное Зелье Прыгучести продлённое', id: 'lingering_potion{Potion:long_leaping}'},
{ name: 'Туманное Зелье Прыгучести усиленное', id: 'lingering_potion{Potion:strong_leaping}'},
{ name: 'Туманное Зелье Регенерации', id: 'lingering_potion{Potion:regeneration}'},
{ name: 'Туманное Зелье Регенерации продлённое', id: 'lingering_potion{Potion:long_regeneration}'},
{ name: 'Туманное Зелье Регенерации усиленное', id: 'lingering_potion{Potion:strong_regeneration}'},
{ name: 'Туманное Зелье Силы', id: 'lingering_potion{Potion:strength}'},
{ name: 'Туманное Зелье Силы продлённое', id: 'lingering_potion{Potion:long_strength}'},
{ name: 'Туманное Зелье Силы усиленное', id: 'lingering_potion{Potion:strong_strength}'},
{ name: 'Туманное Зелье Слабости', id: 'lingering_potion{Potion:weakness}'},
{ name: 'Туманное Зелье Слабости продлённое', id: 'lingering_potion{Potion:long_weakness}'},
{ name: 'Туманное Зелье Стремительности', id: 'lingering_potion{Potion:swiftness}'},
{ name: 'Туманное Зелье Стремительности продлённое', id: 'lingering_potion{Potion:long_swiftness}'},
{ name: 'Туманное Зелье Стремительности усиленное', id: 'lingering_potion{Potion:strong_swiftness}'},
{ name: 'Туманное Зелье Черепашьей мощи', id: 'lingering_potion{Potion:turtle_master}'},
{ name: 'Туманное Зелье Черепашьей мощи продлённое', id: 'lingering_potion{Potion:long_turtle_master}'},
{ name: 'Туманное Зелье Черепашьей мощи усиленное', id: 'lingering_potion{Potion:strong_turtle_master}'},
{ name: 'Туф', id: 'tuff'},
{ name: 'Тушёные грибы', id: 'mushroom_stew'},
{ name: 'Тушёный кролик', id: 'rabbit_stew'},
{ name: 'Тыква', id: 'pumpkin'},
{ name: 'Тыквенный пирог', id: 'pumpkin_pie'},
{ name: 'Тёмный дуб', id: 'dark_oak_wood'},
{ name: 'Тёмный призмарин', id: 'dark_prismarine'},
{ name: 'Угленосный глубинный сланец', id: 'deepslate_coal_ore'},
{ name: 'Уголь', id: 'coal'},
{ name: 'Угольная руда', id: 'coal_ore'},
{ name: 'Угольный блок', id: 'coal_block'},
{ name: 'Удочка', id: 'fishing_rod'},
{ name: 'Удочка с искажённым грибом', id: 'warped_fungus_on_a_stick'},
{ name: 'Удочка с морковкой', id: 'carrot_on_a_stick'},
{ name: 'Узор флага Глобус', id: 'globe_banner_pattern'},
{ name: 'Узор флага Крипер', id: 'creeper_banner_pattern'},
{ name: 'Узор флага Нечто', id: 'mojang_banner_pattern'},
{ name: 'Узор флага Рыло', id: 'piglin_banner_pattern'},
{ name: 'Узор флага Цветок', id: 'flower_banner_pattern'},
{ name: 'Узор флага Череп', id: 'skull_banner_pattern'},
{ name: 'Узорчатая ваза', id: 'decorated_pot'},
{ name: 'Укреплённый глубинный сланец', id: 'reinforced_deepslate'},
{ name: 'Улей', id: 'beehive'},
{ name: 'Факел', id: 'torch'},
{ name: 'Факел душ', id: 'soul_torch'},
{ name: 'Факельник', id: 'torchflower'},
{ name: 'Фейерверк 1', id: 'firework_rocket{Fireworks:{Flight:1b}}'},
{ name: 'Фейерверк 2', id: 'firework_rocket{Fireworks:{Flight:2b}}'},
{ name: 'Фейерверк 3', id: 'firework_rocket{Fireworks:{Flight:3b}}'},
{ name: 'Фиолетовая глазурованная керамика', id: 'purple_glazed_terracotta'},
{ name: 'Фиолетовая керамика', id: 'purple_terracotta'},
{ name: 'Фиолетовая кровать', id: 'purple_bed'},
{ name: 'Фиолетовая свеча', id: 'purple_candle'},
{ name: 'Фиолетовая стеклянная панель', id: 'purple_stained_glass_pane'},
{ name: 'Фиолетовая шерсть', id: 'purple_wool'},
{ name: 'Фиолетовое стекло', id: 'purple_stained_glass'},
{ name: 'Фиолетовый бетон', id: 'purple_concrete'},
{ name: 'Фиолетовый ковёр', id: 'purple_carpet'},
{ name: 'Фиолетовый краситель', id: 'purple_dye'},
{ name: 'Фиолетовый сухой бетон', id: 'purple_concrete_powder'},
{ name: 'Фиолетовый флаг', id: 'purple_banner'},
{ name: 'Фиолетовый шалкеровый ящик', id: 'purple_shulker_box'},
{ name: 'Фонарь', id: 'lantern'},
{ name: 'Фонарь душ', id: 'soul_lantern'},
{ name: 'Хаустония серая', id: 'azure_bluet'},
{ name: 'Хвоя', id: 'spruce_leaves'},
{ name: 'Хлеб', id: 'bread'},
{ name: 'Хорус', id: 'chorus_plant'},
{ name: 'Цветок хоруса', id: 'chorus_flower'},
{ name: 'Цветочный горшок', id: 'flower_pot'},
{ name: 'Цветущая азалия', id: 'flowering_azalea'},
{ name: 'Цветущий аметист', id: 'budding_amethyst'},
{ name: 'Цепь', id: 'chain'},
{ name: 'Чародейская книга Бесконечность', id: 'enchanted_book{StoredEnchantments:[{id:infinity,lvl:1}]}'},
{ name: 'Чародейская книга Бич членистоногих 1', id: 'enchanted_book{StoredEnchantments:[{id:bane_of_arthropods,lvl:1}]}'},
{ name: 'Чародейская книга Бич членистоногих 2', id: 'enchanted_book{StoredEnchantments:[{id:bane_of_arthropods,lvl:2}]}'},
{ name: 'Чародейская книга Бич членистоногих 3', id: 'enchanted_book{StoredEnchantments:[{id:bane_of_arthropods,lvl:3}]}'},
{ name: 'Чародейская книга Бич членистоногих 4', id: 'enchanted_book{StoredEnchantments:[{id:bane_of_arthropods,lvl:4}]}'},
{ name: 'Чародейская книга Бич членистоногих 5', id: 'enchanted_book{StoredEnchantments:[{id:bane_of_arthropods,lvl:5}]}'},
{ name: 'Чародейская книга Быстрая перезарядка 1', id: 'enchanted_book{StoredEnchantments:[{id:quick_charge,lvl:1}]}'},
{ name: 'Чародейская книга Быстрая перезарядка 2', id: 'enchanted_book{StoredEnchantments:[{id:quick_charge,lvl:2}]}'},
{ name: 'Чародейская книга Быстрая перезарядка 3', id: 'enchanted_book{StoredEnchantments:[{id:quick_charge,lvl:3}]}'},
{ name: 'Чародейская книга Везучий рыбак 1', id: 'enchanted_book{StoredEnchantments:[{id:luck_of_the_sea,lvl:1}]}'},
{ name: 'Чародейская книга Везучий рыбак 2', id: 'enchanted_book{StoredEnchantments:[{id:luck_of_the_sea,lvl:2}]}'},
{ name: 'Чародейская книга Везучий рыбак 3', id: 'enchanted_book{StoredEnchantments:[{id:luck_of_the_sea,lvl:3}]}'},
{ name: 'Чародейская книга Верность 1', id: 'enchanted_book{StoredEnchantments:[{id:loyalty,lvl:1}]}'},
{ name: 'Чародейская книга Верность 2', id: 'enchanted_book{StoredEnchantments:[{id:loyalty,lvl:2}]}'},
{ name: 'Чародейская книга Верность 3', id: 'enchanted_book{StoredEnchantments:[{id:loyalty,lvl:3}]}'},
{ name: 'Чародейская книга Взрывоустойчивость 1', id: 'enchanted_book{StoredEnchantments:[{id:blast_protection,lvl:1}]}'},
{ name: 'Чародейская книга Взрывоустойчивость 2', id: 'enchanted_book{StoredEnchantments:[{id:blast_protection,lvl:2}]}'},
{ name: 'Чародейская книга Взрывоустойчивость 3', id: 'enchanted_book{StoredEnchantments:[{id:blast_protection,lvl:3}]}'},
{ name: 'Чародейская книга Взрывоустойчивость 4', id: 'enchanted_book{StoredEnchantments:[{id:blast_protection,lvl:4}]}'},
{ name: 'Чародейская книга Воспламенение', id: 'enchanted_book{StoredEnchantments:[{id:flame,lvl:1}]}'},
{ name: 'Чародейская книга Громовержец', id: 'enchanted_book{StoredEnchantments:[{id:channeling,lvl:1}]}'},
{ name: 'Чародейская книга Добыча 1', id: 'enchanted_book{StoredEnchantments:[{id:looting,lvl:1}]}'},
{ name: 'Чародейская книга Добыча 2', id: 'enchanted_book{StoredEnchantments:[{id:looting,lvl:2}]}'},
{ name: 'Чародейская книга Добычаа 3', id: 'enchanted_book{StoredEnchantments:[{id:looting,lvl:3}]}'},
{ name: 'Чародейская книга Заговор огня 1', id: 'enchanted_book{StoredEnchantments:[{id:fire_aspect,lvl:1}]}'},
{ name: 'Чародейская книга Заговор огня 2', id: 'enchanted_book{StoredEnchantments:[{id:fire_aspect,lvl:2}]}'},
{ name: 'Чародейская книга Защита 1', id: 'enchanted_book{StoredEnchantments:[{id:protection,lvl:1}]}'},
{ name: 'Чародейская книга Защита 2', id: 'enchanted_book{StoredEnchantments:[{id:protection,lvl:2}]}'},
{ name: 'Чародейская книга Защита 3', id: 'enchanted_book{StoredEnchantments:[{id:protection,lvl:3}]}'},
{ name: 'Чародейская книга Защита 4', id: 'enchanted_book{StoredEnchantments:[{id:protection,lvl:4}]}'},
{ name: 'Чародейская книга Защита от снарядов 1', id: 'enchanted_book{StoredEnchantments:[{id:projectile_protection,lvl:1}]}'},
{ name: 'Чародейская книга Защита от снарядов 2', id: 'enchanted_book{StoredEnchantments:[{id:projectile_protection,lvl:2}]}'},
{ name: 'Чародейская книга Защита от снарядов 3', id: 'enchanted_book{StoredEnchantments:[{id:projectile_protection,lvl:3}]}'},
{ name: 'Чародейская книга Защита от снарядов 4', id: 'enchanted_book{StoredEnchantments:[{id:projectile_protection,lvl:4}]}'},
{ name: 'Чародейская книга Ледоход 1', id: 'enchanted_book{StoredEnchantments:[{id:frost_walker,lvl:1}]}'},
{ name: 'Чародейская книга Ледоход 2', id: 'enchanted_book{StoredEnchantments:[{id:frost_walker,lvl:2}]}'},
{ name: 'Чародейская книга Небесная кара 1', id: 'enchanted_book{StoredEnchantments:[{id:smite,lvl:1}]}'},
{ name: 'Чародейская книга Небесная кара 2', id: 'enchanted_book{StoredEnchantments:[{id:smite,lvl:2}]}'},
{ name: 'Чародейская книга Небесная кара 3', id: 'enchanted_book{StoredEnchantments:[{id:smite,lvl:3}]}'},
{ name: 'Чародейская книга Небесная кара 4', id: 'enchanted_book{StoredEnchantments:[{id:smite,lvl:4}]}'},
{ name: 'Чародейская книга Небесная кара 5', id: 'enchanted_book{StoredEnchantments:[{id:smite,lvl:5}]}'},
{ name: 'Чародейская книга Невесомость 1', id: 'enchanted_book{StoredEnchantments:[{id:feather_falling,lvl:1}]}'},
{ name: 'Чародейская книга Невесомость 2', id: 'enchanted_book{StoredEnchantments:[{id:feather_falling,lvl:2}]}'},
{ name: 'Чародейская книга Невесомость 3', id: 'enchanted_book{StoredEnchantments:[{id:feather_falling,lvl:3}]}'},
{ name: 'Чародейская книга Невесомость 4', id: 'enchanted_book{StoredEnchantments:[{id:feather_falling,lvl:4}]}'},
{ name: 'Чародейская книга Огнеупорность 1', id: 'enchanted_book{StoredEnchantments:[{id:fire_protection,lvl:1}]}'},
{ name: 'Чародейская книга Огнеупорность 2', id: 'enchanted_book{StoredEnchantments:[{id:fire_protection,lvl:2}]}'},
{ name: 'Чародейская книга Огнеупорность 3', id: 'enchanted_book{StoredEnchantments:[{id:fire_protection,lvl:3}]}'},
{ name: 'Чародейская книга Огнеупорность 4', id: 'enchanted_book{StoredEnchantments:[{id:fire_protection,lvl:4}]}'},
{ name: 'Чародейская книга Острота 1', id: 'enchanted_book{StoredEnchantments:[{id:sharpness,lvl:1}]}'},
{ name: 'Чародейская книга Острота 2', id: 'enchanted_book{StoredEnchantments:[{id:sharpness,lvl:2}]}'},
{ name: 'Чародейская книга Острота 3', id: 'enchanted_book{StoredEnchantments:[{id:sharpness,lvl:3}]}'},
{ name: 'Чародейская книга Острота 4', id: 'enchanted_book{StoredEnchantments:[{id:sharpness,lvl:4}]}'},
{ name: 'Чародейская книга Острота 5', id: 'enchanted_book{StoredEnchantments:[{id:sharpness,lvl:5}]}'},
{ name: 'Чародейская книга Отдача 1', id: 'enchanted_book{StoredEnchantments:[{id:knockback,lvl:1}]}'},
{ name: 'Чародейская книга Отдача 2', id: 'enchanted_book{StoredEnchantments:[{id:knockback,lvl:2}]}'},
{ name: 'Чародейская книга Откидывание 1', id: 'enchanted_book{StoredEnchantments:[{id:punch,lvl:1}]}'},
{ name: 'Чародейская книга Откидывание 2', id: 'enchanted_book{StoredEnchantments:[{id:punch,lvl:2}]}'},
{ name: 'Чародейская книга Подводная ходьба 1', id: 'enchanted_book{StoredEnchantments:[{id:depth_strider,lvl:1}]}'},
{ name: 'Чародейская книга Подводная ходьба 2', id: 'enchanted_book{StoredEnchantments:[{id:depth_strider,lvl:2}]}'},
{ name: 'Чародейская книга Подводная ходьба 3', id: 'enchanted_book{StoredEnchantments:[{id:depth_strider,lvl:3}]}'},
{ name: 'Чародейская книга Подводник', id: 'enchanted_book{StoredEnchantments:[{id:aqua_affinity,lvl:1}]}'},
{ name: 'Чародейская книга Подводное дыхание 1', id: 'enchanted_book{StoredEnchantments:[{id:respiration,lvl:1}]}'},
{ name: 'Чародейская книга Подводное дыхание 2', id: 'enchanted_book{StoredEnchantments:[{id:respiration,lvl:2}]}'},
{ name: 'Чародейская книга Подводное дыхание 3', id: 'enchanted_book{StoredEnchantments:[{id:respiration,lvl:3}]}'},
{ name: 'Чародейская книга Починка', id: 'enchanted_book{StoredEnchantments:[{id:mending,lvl:1}]}'},
{ name: 'Чародейская книга Приманка 1', id: 'enchanted_book{StoredEnchantments:[{id:lure,lvl:1}]}'},
{ name: 'Чародейская книга Приманка 2', id: 'enchanted_book{StoredEnchantments:[{id:lure,lvl:2}]}'},
{ name: 'Чародейская книга Приманка 3', id: 'enchanted_book{StoredEnchantments:[{id:lure,lvl:3}]}'},
{ name: 'Чародейская книга Проворство 1', id: 'enchanted_book{StoredEnchantments:[{id:swift_sneak,lvl:1}]}'},
{ name: 'Чародейская книга Проворство 2', id: 'enchanted_book{StoredEnchantments:[{id:swift_sneak,lvl:2}]}'},
{ name: 'Чародейская книга Проворство 3', id: 'enchanted_book{StoredEnchantments:[{id:swift_sneak,lvl:3}]}'},
{ name: 'Чародейская книга Проклятие несъёмности', id: 'enchanted_book{StoredEnchantments:[{id:binding_curse,lvl:1}]}'},
{ name: 'Чародейская книга Проклятие утраты', id: 'enchanted_book{StoredEnchantments:[{id:vanishing_curse,lvl:1}]}'},
{ name: 'Чародейская книга Пронзатель 1', id: 'enchanted_book{StoredEnchantments:[{id:impaling,lvl:1}]}'},
{ name: 'Чародейская книга Пронзатель 2', id: 'enchanted_book{StoredEnchantments:[{id:impaling,lvl:2}]}'},
{ name: 'Чародейская книга Пронзатель 3', id: 'enchanted_book{StoredEnchantments:[{id:impaling,lvl:3}]}'},
{ name: 'Чародейская книга Пронзатель 4', id: 'enchanted_book{StoredEnchantments:[{id:impaling,lvl:4}]}'},
{ name: 'Чародейская книга Пронзатель 5', id: 'enchanted_book{StoredEnchantments:[{id:impaling,lvl:5}]}'},
{ name: 'Чародейская книга Пронзающая стрела 1', id: 'enchanted_book{StoredEnchantments:[{id:piercing,lvl:1}]}'},
{ name: 'Чародейская книга Пронзающая стрела 2', id: 'enchanted_book{StoredEnchantments:[{id:piercing,lvl:2}]}'},
{ name: 'Чародейская книга Пронзающая стрела 3', id: 'enchanted_book{StoredEnchantments:[{id:piercing,lvl:3}]}'},
{ name: 'Чародейская книга Пронзающая стрела 4', id: 'enchanted_book{StoredEnchantments:[{id:piercing,lvl:4}]}'},
{ name: 'Чародейская книга Прочность 1', id: 'enchanted_book{StoredEnchantments:[{id:unbreaking,lvl:1}]}'},
{ name: 'Чародейская книга Прочность 2', id: 'enchanted_book{StoredEnchantments:[{id:unbreaking,lvl:2}]}'},
{ name: 'Чародейская книга Прочность 3', id: 'enchanted_book{StoredEnchantments:[{id:unbreaking,lvl:3}]}'},
{ name: 'Чародейская книга Разящий клинок 1', id: 'enchanted_book{StoredEnchantments:[{id:sweeping,lvl:1}]}'},
{ name: 'Чародейская книга Разящий клинок 2', id: 'enchanted_book{StoredEnchantments:[{id:sweeping,lvl:2}]}'},
{ name: 'Чародейская книга Разящий клинок 3', id: 'enchanted_book{StoredEnchantments:[{id:sweeping,lvl:3}]}'},
{ name: 'Чародейская книга Сила 1', id: 'enchanted_book{StoredEnchantments:[{id:power,lvl:1}]}'},
{ name: 'Чародейская книга Сила 2', id: 'enchanted_book{StoredEnchantments:[{id:power,lvl:2}]}'},
{ name: 'Чародейская книга Сила 3', id: 'enchanted_book{StoredEnchantments:[{id:power,lvl:3}]}'},
{ name: 'Чародейская книга Сила 4', id: 'enchanted_book{StoredEnchantments:[{id:power,lvl:4}]}'},
{ name: 'Чародейская книга Сила 5', id: 'enchanted_book{StoredEnchantments:[{id:power,lvl:5}]}'},
{ name: 'Чародейская книга Скорость души 1', id: 'enchanted_book{StoredEnchantments:[{id:soul_speed,lvl:1}]}'},
{ name: 'Чародейская книга Скорость души 2', id: 'enchanted_book{StoredEnchantments:[{id:soul_speed,lvl:2}]}'},
{ name: 'Чародейская книга Скорость души 3', id: 'enchanted_book{StoredEnchantments:[{id:soul_speed,lvl:3}]}'},
{ name: 'Чародейская книга Тройной выстрел', id: 'enchanted_book{StoredEnchantments:[{id:multishot,lvl:1}]}'},
{ name: 'Чародейская книга Тягун 1', id: 'enchanted_book{StoredEnchantments:[{id:riptide,lvl:1}]}'},
{ name: 'Чародейская книга Тягун 2', id: 'enchanted_book{StoredEnchantments:[{id:riptide,lvl:2}]}'},
{ name: 'Чародейская книга Тягун 3', id: 'enchanted_book{StoredEnchantments:[{id:riptide,lvl:3}]}'},
{ name: 'Чародейская книга Удача 1', id: 'enchanted_book{StoredEnchantments:[{id:fortune,lvl:1}]}'},
{ name: 'Чародейская книга Удача 2', id: 'enchanted_book{StoredEnchantments:[{id:fortune,lvl:2}]}'},
{ name: 'Чародейская книга Удача 3', id: 'enchanted_book{StoredEnchantments:[{id:fortune,lvl:3}]}'},
{ name: 'Чародейская книга Шипы 1', id: 'enchanted_book{StoredEnchantments:[{id:thorns,lvl:1}]}'},
{ name: 'Чародейская книга Шипы 2', id: 'enchanted_book{StoredEnchantments:[{id:thorns,lvl:2}]}'},
{ name: 'Чародейская книга Шипы 3', id: 'enchanted_book{StoredEnchantments:[{id:thorns,lvl:3}]}'},
{ name: 'Чародейская книга Шёлковое касание', id: 'enchanted_book{StoredEnchantments:[{id:silk_touch,lvl:1}]}'},
{ name: 'Чародейская книга Эффективность 1', id: 'enchanted_book{StoredEnchantments:[{id:efficiency,lvl:1}]}'},
{ name: 'Чародейская книга Эффективность 2', id: 'enchanted_book{StoredEnchantments:[{id:efficiency,lvl:2}]}'},
{ name: 'Чародейская книга Эффективность 3', id: 'enchanted_book{StoredEnchantments:[{id:efficiency,lvl:3}]}'},
{ name: 'Чародейская книга Эффективность 4', id: 'enchanted_book{StoredEnchantments:[{id:efficiency,lvl:4}]}'},
{ name: 'Чародейская книга Эффективность 5', id: 'enchanted_book{StoredEnchantments:[{id:efficiency,lvl:5}]}'},
{ name: 'Чародейский стол', id: 'enchanting_table'},
{ name: 'Часы', id: 'clock'},
{ name: 'Череп', id: 'skeleton_skull'},
{ name: 'Череп визер-скелета', id: 'wither_skeleton_skull'},
{ name: 'Черепаший панцирь', id: 'turtle_helmet'},
{ name: 'Черепашье яйцо', id: 'turtle_egg'},
{ name: 'Чернильный мешок', id: 'ink_sac'},
{ name: 'Чернит', id: 'blackstone'},
{ name: 'Чернитная ограда', id: 'blackstone_wall'},
{ name: 'Чернитная плита', id: 'blackstone_slab'},
{ name: 'Чернитные ступеньки', id: 'blackstone_stairs'},
{ name: 'Чистая карта', id: 'map'},
{ name: 'Чёрная глазурованная керамика', id: 'black_glazed_terracotta'},
{ name: 'Чёрная керамика', id: 'black_terracotta'},
{ name: 'Чёрная кровать', id: 'black_bed'},
{ name: 'Чёрная свеча', id: 'black_candle'},
{ name: 'Чёрная стеклянная панель', id: 'black_stained_glass_pane'},
{ name: 'Чёрная шерсть', id: 'black_wool'},
{ name: 'Чёрное стекло', id: 'black_stained_glass'},
{ name: 'Чёрный бетон', id: 'black_concrete'},
{ name: 'Чёрный ковёр', id: 'black_carpet'},
{ name: 'Чёрный краситель', id: 'black_dye'},
{ name: 'Чёрный сухой бетон', id: 'black_concrete_powder'},
{ name: 'Чёрный флаг', id: 'black_banner'},
{ name: 'Чёрный шалкеровый ящик', id: 'black_shulker_box'},
{ name: 'Шалкеровый ящик', id: 'shulker_box'},
{ name: 'Щит', id: 'shield'},
{ name: 'Щиток', id: 'scute'},
{ name: 'Элитры', id: 'elytra'},
{ name: 'Эндер-жемчуг', id: 'ender_pearl'},
{ name: 'Эндер-сундук', id: 'ender_chest'},
{ name: 'Эндерняк', id: 'end_stone'},
{ name: 'Эндерняковые кирпичи', id: 'end_stone_bricks'},
{ name: 'Энергорельсы', id: 'powered_rail'},
{ name: 'Яблоко', id: 'apple'},
{ name: 'Ядовитый картофель', id: 'poisonous_potato'},
{ name: 'Яйцо', id: 'egg'},
{ name: 'Яйцо дракона', id: 'dragon_egg'},
{ name: 'Яйцо дракона', id: 'dragon_egg'},
{ name: 'Яйцо нюхача', id: 'sniffer_egg'},
{ name: 'Яйцо призыва аксолотля', id: 'axolotl_spawn_egg'},
{ name: 'Яйцо призыва белого медведя', id: 'polar_bear_spawn_egg'},
{ name: 'Яйцо призыва брутального пиглина', id: 'piglin_brute_spawn_egg'},
{ name: 'Яйцо призыва ведьмы', id: 'witch_spawn_egg'},
{ name: 'Яйцо призыва верблюда', id: 'camel_spawn_egg'},
{ name: 'Яйцо призыва визер-скелета', id: 'wither_skeleton_spawn_egg'},
{ name: 'Яйцо призыва визера', id: 'wither_spawn_egg'},
{ name: 'Яйцо призыва волка', id: 'wolf_spawn_egg'},
{ name: 'Яйцо призыва вредины', id: 'vex_spawn_egg'},
{ name: 'Яйцо призыва всполоха', id: 'blaze_spawn_egg'},
{ name: 'Яйцо призыва гаста', id: 'ghast_spawn_egg'},
{ name: 'Яйцо призыва головастика', id: 'tadpole_spawn_egg'},
{ name: 'Яйцо призыва дельфина', id: 'dolphin_spawn_egg'},
{ name: 'Яйцо призыва древнего стража', id: 'elder_guardian_spawn_egg'},
{ name: 'Яйцо призыва железного голема', id: 'iron_golem_spawn_egg'},
{ name: 'Яйцо призыва заклинателя', id: 'evoker_spawn_egg'},
{ name: 'Яйцо призыва зимогора', id: 'stray_spawn_egg'},
{ name: 'Яйцо призыва зоглина', id: 'zoglin_spawn_egg'},
{ name: 'Яйцо призыва зомби', id: 'zombie_spawn_egg'},
{ name: 'Яйцо призыва зомбифицированного пиглина', id: 'zombified_piglin_spawn_egg'},
{ name: 'Яйцо призыва иглобрюха', id: 'pufferfish_spawn_egg'},
{ name: 'Яйцо призыва кадавра', id: 'husk_spawn_egg'},
{ name: 'Яйцо призыва козы', id: 'goat_spawn_egg'},
{ name: 'Яйцо призыва коровы', id: 'cow_spawn_egg'},
{ name: 'Яйцо призыва кошки', id: 'cat_spawn_egg'},
{ name: 'Яйцо призыва крестьянина', id: 'villager_spawn_egg'},
{ name: 'Яйцо призыва крестьянина-зомби', id: 'zombie_villager_spawn_egg'},
{ name: 'Яйцо призыва крипера', id: 'creeper_spawn_egg'},
{ name: 'Яйцо призыва кролика', id: 'rabbit_spawn_egg'},
{ name: 'Яйцо призыва курицы', id: 'chicken_spawn_egg'},
{ name: 'Яйцо призыва лавомерки', id: 'strider_spawn_egg'},
{ name: 'Яйцо призыва ламы', id: 'llama_spawn_egg'},
{ name: 'Яйцо призыва ламы торговца', id: 'trader_llama_spawn_egg'},
{ name: 'Яйцо призыва летучей мыши', id: 'bat_spawn_egg'},
{ name: 'Яйцо призыва лисицы', id: 'fox_spawn_egg'},
{ name: 'Яйцо призыва лосося', id: 'salmon_spawn_egg'},
{ name: 'Яйцо призыва лошади', id: 'horse_spawn_egg'},
{ name: 'Яйцо призыва лошади-зомби', id: 'zombie_horse_spawn_egg'},
{ name: 'Яйцо призыва лошади-скелета', id: 'skeleton_horse_spawn_egg'},
{ name: 'Яйцо призыва лягушки', id: 'frog_spawn_egg'},
{ name: 'Яйцо призыва магмового куба', id: 'magma_cube_spawn_egg'},
{ name: 'Яйцо призыва мула', id: 'mule_spawn_egg'},
{ name: 'Яйцо призыва муухомора', id: 'mooshroom_spawn_egg'},
{ name: 'Яйцо призыва нюхача', id: 'sniffer_spawn_egg'},
{ name: 'Яйцо призыва овцы', id: 'sheep_spawn_egg'},
{ name: 'Яйцо призыва осла', id: 'donkey_spawn_egg'},
{ name: 'Яйцо призыва оцелота', id: 'ocelot_spawn_egg'},
{ name: 'Яйцо призыва панды', id: 'panda_spawn_egg'},
{ name: 'Яйцо призыва паука', id: 'spider_spawn_egg'},
{ name: 'Яйцо призыва пещерного паука', id: 'cave_spider_spawn_egg'},
{ name: 'Яйцо призыва пиглина', id: 'piglin_spawn_egg'},
{ name: 'Яйцо призыва поборника', id: 'vindicator_spawn_egg'},
{ name: 'Яйцо призыва попугая', id: 'parrot_spawn_egg'},
{ name: 'Яйцо призыва пчелы', id: 'bee_spawn_egg'},
{ name: 'Яйцо призыва разбойника', id: 'pillager_spawn_egg'},
{ name: 'Яйцо призыва разорителя', id: 'ravager_spawn_egg'},
{ name: 'Яйцо призыва светящегося спрута', id: 'glow_squid_spawn_egg'},
{ name: 'Яйцо призыва свиньи', id: 'pig_spawn_egg'},
{ name: 'Яйцо призыва скелета', id: 'skeleton_spawn_egg'},
{ name: 'Яйцо призыва слизня', id: 'slime_spawn_egg'},
{ name: 'Яйцо призыва снежного голема', id: 'snow_golem_spawn_egg'},
{ name: 'Яйцо призыва спрута', id: 'squid_spawn_egg'},
{ name: 'Яйцо призыва стража', id: 'guardian_spawn_egg'},
{ name: 'Яйцо призыва странствующего торговца', id: 'wandering_trader_spawn_egg'},
{ name: 'Яйцо призыва тихони', id: 'allay_spawn_egg'},
{ name: 'Яйцо призыва трески', id: 'cod_spawn_egg'},
{ name: 'Яйцо призыва тропической рыбы', id: 'tropical_fish_spawn_egg'},
{ name: 'Яйцо призыва утопленника', id: 'drowned_spawn_egg'},
{ name: 'Яйцо призыва фантома', id: 'phantom_spawn_egg'},
{ name: 'Яйцо призыва хоглина', id: 'hoglin_spawn_egg'},
{ name: 'Яйцо призыва хранителя', id: 'warden_spawn_egg'},
{ name: 'Яйцо призыва черепахи', id: 'turtle_spawn_egg'},
{ name: 'Яйцо призыва чешуйницы', id: 'silverfish_spawn_egg'},
{ name: 'Яйцо призыва шалкера', id: 'shulker_spawn_egg'},
{ name: 'Яйцо призыва Эндер-дракона', id: 'ender_dragon_spawn_egg'},
{ name: 'Яйцо призыва эндермена', id: 'enderman_spawn_egg'},
{ name: 'Яйцо призыва эндермита', id: 'endermite_spawn_egg'},
{ name: 'Якорь возрождения', id: 'respawn_anchor'},
    ]}
}

